### ISSUE TITLE
Multi character letters in other languages

### ISSUE THREAD

**Issue by jacbrixey** [cwackerfuss/react-wordle#105]
Hello! I am trying to use this project to make Wordle for another language but I am a bit confused on how to do that. There are only 3 special characters, "a̱", "i̱" and "o̱", all two unicode characters. Currently in the game, the keyboard shows each of the characters in separate boxes when the letter character is selected. How do I make them only appear as one? Where do I make that change in the code? Thanks in advance!

**Comment by muhelen** [comment]
You need to normalize Unicode strings to combine the characters. Refer to the solutions here : https://withblue.ink/2019/03/11/why-you-need-to-normalize-unicode-strings.html

**Comment by jacbrixey** [comment]
Thanks for the response! How do I apply that here?

**Comment by MayankVikash** [comment]
Thanks @muhelen 
Even I was facing this, btw are you a reactjs expert?
I am learning react, and having some issues, like e-slint collide and lots more, can you tell me what to do?

**Comment by trosel** [comment]
https://github.com/hannahcode/word-guessing-game/issues/87
