### ISSUE TITLE
Different words on the same day

### ISSUE THREAD

**Issue by nankigrewal** [cwackerfuss/react-wordle#114]
Sometimes, friends and I notice we get different words for iterations on the same day. For example, a friend today got a different word from the rest of us, then refreshed and got a whole new game (rather than having to wait for a day) and got the same word as us.

Platform the issue is seen on: Safari on iPhone.

**Comment by diondiondion** [comment]
This should eventually be solved by #73

**Comment by MohammedAlrozzi** [comment]
Are you and your friends located in the same time zone? the word change for everyone at different time (local midnight), so it is different time depending where you are located.

**Comment by cwackerfuss** [comment]
Closing this, it's referenced in #73 which is where we're tracking this request
