### ISSUE TITLE
Valid guesses

### ISSUE THREAD

**Issue by craiglockwood** [cwackerfuss/react-wordle#116]
It seems the validGuesses file is missing a lot of common words. It seems that that this may be the valid guesses file from Wordle (which is great), but they are missing the words from the Wordle wordlist. 

Maybe they could be combined? 

It may be a case of having to remove the word from validGuesses file when you want to add it to the wordlist but that wouldn't be too much of a problem.

**Comment by teddyh-io** [comment]
I added all missing words from the original wordle into this repo and PR'd. About 2000 extra words. You should be able to close this now.
