### ISSUE TITLE
Compiling a list of projects built using this repo

### ISSUE THREAD

**Issue by cwackerfuss** [cwackerfuss/react-wordle#120]
Hey folks! :)

I've seen a lot of cool projects in the wild built using this code and I wanted to make an effort to compile a list of links and add them to the README.

Here are the ones I know of already:
- https://www.taylordle.com/
- https://converged.yt/primel/
- https://nezza.github.io/syscordle/
- https://www.mathler.com/

Anyone have one they've made or seen they'd like to add?

**Comment by theotarr** [comment]
https://wordle.latindictionary.io

**Comment by leonidasv** [comment]
🙋🏻‍♂️ Yep, mine!

https://stockle.win/

**Comment by MohammedAlrozzi** [comment]
https://kelmaly.com - In Arabic

**Comment by eltaylor1104** [comment]
A The Office themed version! https://dundle.dunmiffcord.com

**Comment by diondiondion** [comment]
In German:

https://woertchen.sofacoach.de

**Comment by M4t1ss** [comment]
Hi! Here's my version in Latvian 🙃
[wordle.lielakeda.lv/](https://wordle.lielakeda.lv/)

**Comment by asirota** [comment]
We are working on one with an AI component @asirota/Wordle-ai

I suppose the word Wordle is off limits now isn't it ?

**Comment by spbyrne** [comment]
I've been working on a [hangman mashup called Murdle](https://murdle.vercel.app/), still a work in progress. 

Thanks for this awesome project! 🙏

**Comment by corroded** [comment]
Working on a dictionary with all video game characters. So far I have a bunch of pokemon and fire emblem heroes characters (and some random Nintendo ones). Looking to add more from other games :)

https://meetmeinouter.space/wordle/

**Comment by Vishkujo** [comment]
I made one based on JoJo's Bizarre Adventure
https://jojo-news.com/fun/jojodle/

**Comment by rishubil** [comment]
This is a mahjong hand version
https://mahjong-handle.update.sh/

**Comment by tirea** [comment]
`'en si lì'ur` ("guess the word") - in Na'vi, the constructed language from James Cameron's AVATAR (2009)

deployed at [https://tirea.learnnavi.org/wordle](https://tirea.learnnavi.org/wordle)

fork repo at [https://github.com/tirea/react-wordle](https://github.com/tirea/react-wordle)

**Comment by jtraverso** [comment]
I'm working on a version with chilean modisms, cities, places, etc, you can see it live in [wordle.cl](https://www.wordle.cl) fork repo https://github.com/jtraverso/wordle.cl

**Comment by lingdocs** [comment]
[Pashtoodle](https://pashtoodle.lingdocs.com): In Pashto

**Comment by muhelen** [comment]
https://omtamil.com/soladle - Tamil version

**Comment by mdanka** [comment]
Hungarian version :)
https://szozat.miklosdanka.com/
https://github.com/mdanka/szozat

**Comment by rwmpelstilzchen** [comment]
Hi,

The maintainer of [Wordles of the World](https://rwmpelstilzchen.gitlab.io/wordles/) here. I added the versions mentioned here to the list. When more are added, please consider making a [merge request](https://gitlab.com/rwmpelstilzchen/wordles).

@cwackerfuss, if you want to add a link to Wordles of the World, that would be great ^_^. I already added there a link to [this list](https://github.com/cwackerfuss/react-wordle#projects-built-using-this-repo), in addition to the particular entries.

Júda

**Comment by abrarhayat** [comment]
Hello! I implemented Anidal, a wordle for animal names. 

Please find my PR [here](https://github.com/cwackerfuss/react-wordle/pull/130)

Deployed [here](https://anidal-abrarhayat.web.app)

**Comment by andrewholding** [comment]
Absolutely brilliant... my version is deployed here https://andrewholding.github.io/gene-wordle/

GitHub here https://github.com/andrewholding/gene-wordle

It's a version for guessing Genes!

**Comment by dmessing** [comment]
Awesome job, very impressed!  If I wanted to host and use this myself, I'd love to give credit and discuss the possibility?  Who is the best person to chat with?

**Comment by rbrignall** [comment]
Numble - a maths-themed wordle, is here:
https://rbrignall.github.io/numble/

**Comment by yuyangchee98** [comment]
Malay wordle:

**Comment by cwackerfuss** [comment]
This is a blast -- yall are incredible! Just updated the readme again with everything here so far.

**Comment by zakarth** [comment]
Just wanted to add in to this list Trekle (treklegame.com) with appropriate credit given on the About page. Thank you so much for this work everyone.

**Comment by bhavesh15184** [comment]
@cwackerfuss I created one for movies https://movie-wordle.vercel.app
It's limited to Indian movies as of now.

**Comment by mmmewk** [comment]
@cwackerfuss I've created one where you solve an entire crossword using the wordle https://crosswordle.co

**Comment by ovisirb** [comment]
Hi, I've also been working on a Romanian version here https://wordle-ro.sirb.net/

**Comment by collabital** [comment]
@cwackerfuss UNLOCOdle for UNLOCODEs.
https://unlocodle.collabital.com/
https://github.com/collabital/unlocodle
Trying to keep up to date with the changes in this project, as I've added more detail to the dictionary and added some extra boxes to mine!

**Comment by lampy12** [comment]
What do i download to use the code but just change the word list so i can use custom word list and make my own theme

**Comment by nandaabiz** [comment]
Javanese version: 
Demo: https://vercel.com/nandaabiz/tlembung
Source: https://github.com/nandaabiz/tlembung

Thanks for your great works!

**Comment by charooxyz** [comment]
**Sindhi** Version
Demo: https://hellosindh.com/sindhal

**Comment by lampy12** [comment]
> This is just for note: Wordle Hub (wiki) now has 'forks' section to list up forks. [Here](https://wordles.miraheze.org/wiki/https://reactle.vercel.app/#forks) is an example for Reactle.

Hello i was wondering what i need to download to run the code and make my own version by changing the word list. then make it on a website

**Comment by lampy12** [comment]
> 
Hello i was wondering what i need to download to run the code and make my own version by changing the word list. then make it on a website

**Comment by Vrisel** [comment]
I made it for Quenya in Korean environment, named 퀘탈레(Quettale): <https://quettale.vercel.app>.
I'm going to make translated pages (in English and maybe also in Quenya?).

(You know, Quenya is one of conlangs, and used by Elves in The Lord of the Rings)

Thanks!!

**Comment by xho** [comment]
Would like to add Parolette in Italian: https://parolette.netlify.app/

I forked the project in January, but since I developed some features and the code diverged so much I can't merge anymore. Anyway thanks a lot to all those who contributed to this project.

**Comment by zedaizd** [comment]
Hi, I made a traditional Chinese version, called 字知之明  
Demo: [https://zedaizd.github.io/zh-char-puzzle/](https://zedaizd.github.io/zh-char-puzzle/)
Repository: [https://github.com/zedaizd/zh-char-puzzle](https://github.com/zedaizd/zh-char-puzzle)

Thanks for your great work and hope everyone here has fun time for making and playing games 🎉

**Comment by gcrichton** [comment]
Cornish (Kernowek) version:
https://gerdle.vext.co.uk/

Currently uses all five letter words extracted from the Cornish Standard Written Form dictionary. May add more from other orthographies.

**Comment by ndench** [comment]
A building/construction themed version: https://buildly.procurepro.co

**Comment by alfoadd** [comment]
🇮🇹 Italian version: https://parolle.it

**Comment by kikychow** [comment]
Hi, I've been working on a Poker Hand version: https://kikychow.github.io/poker-wordle/
Thank you for your great project!

**Comment by PedramH** [comment]
Hi guys. I made a Persian (Farsi) version here:
 [Persian wordle ](persian-wordle.ir)

**Comment by zbennett** [comment]
Harry Potter Version: https://www.harrypotterwordle.com

**Comment by lens0021** [comment]
I know https://www.mugglenet.com/fans-fun/trivia-challenges/wizarding-wordle/ is also a Harry Potter version

**Comment by elmurod1202** [comment]
@cwackerfuss I've created one for **Uzbek language** here: [](http://wordlar.uz/)

**Comment by matthewa313** [comment]
[www.creek-birdle.com](www.creek-birdle.com) -- At my high school we play Wordle but only for bird-related words... I decided to take it step further and program it for the school... Loving the work everyone here is doing.

**Comment by raymond-lin** [comment]
Created 4dle to guess the 4 numbers @ https://4dle.vercel.app

**Comment by Palindromer** [comment]
Ukrainian
https://goroh.pp.ua/games/wordle

**Comment by itcrowd** [comment]
Thank you very much for this code. I've created a radio-themed version for World Radio Day today (13th Feb) to promote UK community (not for profit) radio:

[https://radiole.vercel.app/](https://radiole.vercel.app/)

**Comment by shamayn** [comment]
My Singlish version took off in Singapore :)

https://word-leh.com

Kudos and thanks to this community.

**Comment by oradwell** [comment]
guessing JavaScript libraries: [jazle.quest](https://jazle.quest/)
source: [oradwell/jazle](https://github.com/oradwell/jazle)

**Comment by dgplacenames** [comment]
SPNle (Scottish Place-Name Wordle) currently running at http://maps.gisforthought.com:3000/
Repo: https://github.com/dgplacenames/SPNle
Thanks to everyone who worked on this.

**Comment by NicosHere** [comment]
[Wordle except the word is always farts](https://fartsle.com)

**Comment by jleverenz** [comment]
Thanks for making this!
Birdle - bird emojis - https://birdle.dev
Forked at https://github.com/jleverenz/birdle

**Comment by abae** [comment]
Thanks to you guys, I had a fun weekend 😁
Made a wordle variant where the answer is a word that is 5-letters long after you get rid of its vowels.
Wrdl - https://wrdl-abae.vercel.app/

**Comment by plingbang** [comment]
Non-serious Morse code version: https://plingbang.github.io/morsel/
[Source](https://github.com/plingbang/morsel).

**Comment by AbbyCodeStudio** [comment]
Math Equation: https://nerdlegame.com/
Four wordle: https://www.quordle.com/

**Comment by jpennington-healthguard** [comment]
I made an unnecessary Pokemon variant: https://squirdle-inky.vercel.app/

**Comment by atmospherium** [comment]
I made an unnecessary Pokemon variant: https://squirdle-inky.vercel.app/

**Comment by ftick** [comment]
Competitive Smash: https://randle.vercel.app/

**Comment by rwmpelstilzchen** [comment]
> Competitive Smash: https://randle.vercel.app/

Smash = Super Smash Bros.?

@ftick

**Comment by eraizel** [comment]
hi could you add Brazilian Portuguese to the list o available languages?
https://palabro-silk.vercel.app/

**Comment by purindaisuki** [comment]
Hi, I made a chemical version for guessing the molecular formulae: 
https://purindaisuki.github.io/chemicle/

**Comment by jdzuri** [comment]
Hi! I made a multi language variant with unlimited games (no one for day limit): [https://jordle.jovid.win/](https://jordle.jovid.win/)

I'll very happy if it's added to the list :). Thanks for this awesome repo.

**Comment by LKarel** [comment]
Hi! I made an Estonian version of it:
- Sõnarajad https://sõnar.ajad.ee/

**Comment by bluefencecurtain** [comment]
Hi - Apologies if this is not the right place to ask, but I can see other folks are able to deploy this game using https.  I installed the package and was able to 'npm run start', but my game server is listening on http, not https.  What is the easiest way to change this?

**Comment by kravlost** [comment]
Hi, here's a popular Cornish (Kernewek, using the Standard Written Form orthography) version: https://kerdle.vercel.app/

**Comment by Yongjun042** [comment]
I made a Korean version. 
음들 https://eumdle.pages.dev/
Difference with other korean wordle is it doesn't expand vowel/consonant

**Comment by Yongjun042** [comment]
Korean Wordle 꼬들 is changing its link to https://kordle.kr/ on 2022-02-22 it shoud be updated.

**Comment by louiseadennis** [comment]
Doctor Who Version: https://louiseadennis.github.io/doctor-whordle/

**Comment by ryan-hkg** [comment]
I made a version for Hong Kong Mahjong! It'd be great if you could add this to the list. This repo is amazing!

- 香港麻雀 糊dle: Mahjong hands under Hong Kong rules

[https://hkwudle.vercel.app/](https://hkwudle.vercel.app/)

**Comment by danielors** [comment]
Created one for three letter Federal Agencies -- https://fedle.vercel.app

Thanks for the handy starting point @cwackerfuss !

**Comment by yordl** [comment]
_Never underestimate the power of the Scout's code._ 😄
- https://yordle.quest/

Yordle (League of Legends version) [fork](https://github.com/yordl/yordle)

**Comment by nomin-batsaikhan** [comment]
Hey, a Friends-themed one here: https://wordle.flickonic.com/  😊

**Comment by orisenbazuru** [comment]
Machine learning version using ImageNet dataset 

🎮 https://orisenbazuru.github.io/visionle/

Code 🧑‍💻: https://github.com/orisenbazuru/visionle

**Comment by zussini** [comment]
hi i've done Polish version basing on your repo:
link to the hosted app on AWS: 
http://worple.pl/
link to the cloned github repo with language modifications:
https://github.com/zussini/worPLe
If you would have any additional suggestions i can fulfill them.
Regards

**Comment by travisryan** [comment]
https://carpartle.com
it's for car and car part words.

**Comment by jbalakri1** [comment]
Indian Railways station code version here: https://irfca.org/irfca-wordle/

Thanks for this!

**Comment by Storyyeller** [comment]
Randle: A Wordle variant that starts you with a free random clue to add variety.
https://storyyeller.github.io/react-wordle/

**Comment by olgiz** [comment]
I've been working on [Basketle.com](https://www.basketle.com) a NBA Wordle clone that includes player names, teams, coaches etc :)

**Comment by greyrockinnovations** [comment]
Hey great work with this project @cwackerfuss - thank you!

I made Dronedle - a drone-themed version for drone nerds...
[https://dronedle.com](https://dronedle.com)

**Comment by hakaneskici** [comment]
Awesome work with this project - kudos  @cwackerfuss and other contributors.

I have made a 3-letter Turkish version; available at:
https://www.3harfli.com/

**Comment by nandaabiz** [comment]
A little correction @cwackerfuss 
Mine, TLEMBUNG (https://tlembung.vercel.app/) is in Javanese (part of Indonesia) not Japanese 
https://en.wikipedia.org/wiki/Javanese_language

**Comment by pwahs** [comment]
Hi, I have created a clone where you have to find a Fillomino solution (Fill a number in each cell such that connected cells with the same number form a region as large as the number.)
[Fillominordle](https://pwahs.github.io/fillominordle)

Thanks for publishing your source code and allowing so many creative clones!

**Comment by eraizel** [comment]
> Hi, I have created a clone where you have to find a Fillomino solution (Fill a number in each cell such that connected cells with the same number form a region as large as the number.) [Fillominordle](https://pwahs.github.io/fillominordle)
> 
> Thanks for publishing your source code and allowing so many creative clones!

WOW loved it! instant addicted! please put a link to share your site when your finish the pusszle, if you need help let me know.

**Comment by billybillymc** [comment]
This repo is awesome! I used it to make 18 different TV show-based versions at https://www.bingeclock.com/bingerdle/

Attack on Titan: https://www.bingeclock.com/bingerdle/attack-on-titan/
Breaking Bad: https://www.bingeclock.com/bingerdle/breaking-bad/
Family Guy: https://www.bingeclock.com/bingerdle/family-guy/
Friends: https://www.bingeclock.com/bingerdle/friends-1994/
Futurama: https://www.bingeclock.com/bingerdle/futurama/
Game of Thrones: https://www.bingeclock.com/bingerdle/game-of-thrones/
How I Met Your Mother: https://www.bingeclock.com/bingerdle/how-i-met-your-mother/
JoJo's Bizarre Adventure: https://www.bingeclock.com/bingerdle/jojos-bizarre-adventure/
Lost: https://www.bingeclock.com/bingerdle/lost/
One Piece: https://www.bingeclock.com/bingerdle/one-piece/
Rick and Morty: https://www.bingeclock.com/bingerdle/rick-and-morty/
Riverdale: https://www.bingeclock.com/bingerdle/riverdale/
Seinfeld: https://www.bingeclock.com/bingerdle/seinfeld/
The Simpsons: https://www.bingeclock.com/bingerdle/simpsons/
South Park: https://www.bingeclock.com/bingerdle/south-park/
Stranger Things: https://www.bingeclock.com/bingerdle/stranger-things/
Vikings: https://www.bingeclock.com/bingerdle/vikings/

Also open to requests, if anyone would like to see other series up on Bingerdle.

**Comment by kev1nccw** [comment]
Hi, I have created a color code version of wordle, you might find it at https://kev1nccw.github.io/colorle

Thank you for publishing such an amazing repo!

**Comment by eithe** [comment]
I made a out of the box spin-off where you select between two pictures which in the end sort of determines who you are.

https://twokinds.me/

PR: https://github.com/cwackerfuss/react-wordle/pull/303

**Comment by dategumi** [comment]
Hi, thank you for this repo! I used it to make [Swordle](https://swordle-tkrb.vercel.app/) which is based on Touken Ranbu - a game about swords!

**Comment by UselessNeanderthal** [comment]
I created a wordle based off crypto tickers! Kind of like stockle with crypto. https://cryptle.vercel.app/ is where it is. Thank you so much for sharing this code!

**Comment by intibeer** [comment]
Hey we've created a scholar/academic word version here - [Scholardle](https://scholardle.vercel.app/). (https://github.com/intibeer/scholardle)

**Comment by pnjegan** [comment]
created with 4 letter and its here - https://play.fo4rdle.com 

Thanks

**Comment by xericho** [comment]
Thanks for sharing your code! I created Herdle, a clone that "helps with Wordle". It's not a game but a tool that will suggest words to help you solve Wordle! https://herdle.netlify.app/

**Comment by lucialacourtna** [comment]
Paimordle, based on Genshin Impact :) 
https://paimordle.vercel.app/

**Comment by drrnyip** [comment]
Thanks for sharing the codebase! Here's what I did with it: https://thoddle.vercel.app
Thesaurus + Wordle!

**Comment by HeskayW** [comment]
I made this: https://heskayw.github.io/react-dordle/

Its a Spanish adaptation of Dordle (https://zaratustra.itch.io/dordle)

**Comment by KShammout632** [comment]
Hey! I made https://cinemadle.com
You have to guess the movie based on the frame shown, with a new frame after each incorrect guess made.
Repo: https://github.com/KShammout632/cinemadle

**Comment by QAInsights** [comment]
Hi 👋, I made https://perfdle.vercel.app

Wordle for performance engineers.

**Comment by dschu012** [comment]
https://a.sightwordle.com/

Wordle made using ["sight words"](https://en.wikipedia.org/wiki/Sight_word) for my 5 year old kid. Uses 3/4 letter words and starts off removing a few letters to make it a bit easier.

**Comment by vaxoiva** [comment]
Hello გამარჯობა

In Georgian

  Jordle.ge

**Comment by sldltd** [comment]
Hi, Scots language version (MacWordle) available from 20 March 2022: https://macwordle.co.uk/  Many thanks for sharing the code and making MacWordle possible.

**Comment by Jullan-M** [comment]
Hello, I made a Northern Sami version of wordle - [Šordle](https://folk.ntnu.no/jmlindi/). Thanks for the codebase!
Forked repo can be found here: https://github.com/Jullan-M/word-guess-sme

**Comment by aghasemi** [comment]
Hi. I created Reverdle initially as a joke, but then some friends liked it. 
It's Wordle but in reverse, that is one hast to make as many guesses possible without having one green letter (i.e. one letter in the correct location compared to the hidden solution). Also, your guesses should be far enough from each other for the game to be meaningful. 

Feel free to try it: https://reverdle.now.sh/

**Comment by aghasemi** [comment]
RareWordle: Word guessing with multiple solutions each day where the goal is to find the most obscure one. It is inspired by the TV game show Pointless. 

Each game has multiple solutions all having the same letters.

The goal is to guess the most obsolete word among the words in the solution group in 8 tries. After each guess, the color of the tiles will change to show which common letters you have correctly revealed.

Please note that you will not get any information about the exact location of the letters in the solution, because there are multiple solutions and the position of a letter varies from one to another.

As soon as you suggest a word that has has all 5 common letters, the game ends and your answer will get ranked based on its rarity (inverse frequency) in the English language. You will also see other solutions.

Try: https://rwordle.vercel.app/

**Comment by aiy2002** [comment]
Cyble: Cybersecurity themed wordle 
https://www.mycyberinfo.com/cyble

**Comment by DorkyP** [comment]
Hey! I made one called Syllablordle! I forked your code, then modified the code pretty significantly. 🤣 Thanks for providing an awesome template to work with.
Deployed here: https://syllablordle.com/
Fork here: https://github.com/DorkyP/syllablordle

**Comment by leonardoacropolis** [comment]
Hi

 I've made one called datele for historical dates. 

Brilliant code. Thanks very much. Https://datele.app

Peter

**Comment by acemuzzy** [comment]
I've made one with a twist!  Each row has one piece of (random) misinformation.  

Behold [Confusle](http://confusle.uksouth.cloudapp.azure.com/).

Code at https://github.com/acemuzzy/confusle.

Currently only ~beta, so feedback welcomed!

Oh and I included some k8s snippets FWIW, as I needed them to get it accessible (via DNS) in Azure AKS.

**Comment by asirota** [comment]
Random length answer, much more difficult since you don't know the length of the word. Diffle is at https://hedalu244.github.io/diffle/

**Comment by briglass** [comment]
https://jeffgoldblumle.vercel.app/

Clone where 90% of the time, the answer is Jeff Goldblum

**Comment by Brayman30** [comment]
Biology themed wordie: (https://biordle.vercel.app/)

**Comment by Seflyx** [comment]
Trying out the indonesian language version of this: https://reactle-id.vercel.app/

Pull request from fellow Indonesian is welcome in [the repository](https://github.com/Seflyx/react-wordle-indonesian) because I myself have a hard time compiling the word list.

**Comment by bethfraser** [comment]
Gymdle - gymnastics wordle! I need to add more words though as currently it'll run out in a week! https://gymdle.netlify.app/

**Comment by tangym27** [comment]
Hi, I made
Pawnle -  wordle based off of the television show Parks and Recreation: [https://pawnle.vercel.app/](https://pawnle.vercel.app/) . 
My fork is here: https://github.com/tangym27/pawnle-wordle .

**Comment by aislinp** [comment]
Strayerdle - Wordle based on my history textbook.
https://histordle.vercel.app/

**Comment by BarokDG** [comment]
Lyricle - guess a song from its lyrics.
https://www.lyricle.app/

**Comment by benzaps** [comment]
Hi,

Very nice code.  I've adapted it to a Pennsylvania Dutch version.

[https://padutchdictionary.com/wattli/](url)

Thanks,
Peter

**Comment by Teja36** [comment]
One piece devil fruits version : https://devil-fruitle.vercel.app/

**Comment by RafalKaczor** [comment]
Hello, 

Please add https://compositLe.com - Wordle with composite numbers.  Officially launches today. 

 🎁🇺🇸Happy Independance Day everybody🇺🇸🎁

Inspired by DL Miller and Cojofra's Primel.
Happily made in 🇨🇦

**Comment by igitur** [comment]
Due to reduced capacity, we request you to contribute your downstream implementations via a pull request.

**Comment by igitur** [comment]
> [www.creek-birdle.com](www.creek-birdle.com) -- At my high school we play Wordle but only for bird-related words... I decided to take it step further and program it for the school... Loving the work everyone here is doing.

@matthewa313 Link is dead. Please fix or remove from README
