### ISSUE TITLE
Answer popup overlaps with first guess

### ISSUE THREAD

**Issue by igitur** [cwackerfuss/react-wordle#134]
**Describe the bug**
The rose coloured popup with the answer overlaps with the first guess. Sometimes I want to share my entire board with a friend through screenshots.

**To Reproduce**
Guess all 6 guesses wrong.
Wait for answer to appear.

**Expected behavior**
Answer popup doesn't overlap with anything else. That means allow enough space upfront between the title and the first guess.

**Screenshots**
![image](https://user-images.githubusercontent.com/145854/152953078-17b9c991-f25c-4aed-88ad-632649c43f2e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version Version 1.35.100

**Comment by gbear605** [comment]
This was originally fixed in https://github.com/cwackerfuss/react-wordle/pull/75, but the fix was reverted in https://github.com/cwackerfuss/react-wordle/commit/fcc4510199f7bdf3a5cce3b2d9f09939c38cc5ca

**Comment by TheKnowles** [comment]
Added to https://github.com/cwackerfuss/react-wordle/pull/131

**Comment by igitur** [comment]
@TheKnowles Are you addressing this? Else I'll try prepare a PR.

**Comment by TheKnowles** [comment]
@igitur yes I added the fix to PR 131.

**Comment by cwackerfuss** [comment]
Merged 131, this is fixed!
