### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by techpluscraft** [cwackerfuss/react-wordle#140]
**Is your feature request related to a problem? Please describe.**
I have friends that are Russian and they really enjoy that game and I was wondering if som people could help me with a Russian translation?

**Describe the solution you'd like**
Some people to help me with a Russian version

**Describe alternatives you've considered**
More buttons since the Russian alphabet has more letters

**Additional context**

**Comment by cwackerfuss** [comment]
There is now a russian version listed in the readme
