### ISSUE TITLE
Theme bar, Language Selection

### ISSUE THREAD

**Issue by techpluscraft** [cwackerfuss/react-wordle#141]
**Is your feature request related to a problem? Please describe.**

It’s really hard to find and switch between different themes of wordle

**Describe the solution you'd like**

A button were you can select a theme and a language select bar

**Describe alternatives you've considered**

Language button and theme button with a drop down of themes

**Additional context**

**Comment by cwackerfuss** [comment]
This is outside the scope of the project -- other folks build and maintain different versions of the project in separate repositories. There is a list in the readme of derivative projects.

PS we just added a Russian one @techpluscraft !
