### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by techpluscraft** [cwackerfuss/react-wordle#143]
It's hard to make custom light themes so I was thinking in app.css adding something like html.light

**Comment by techpluscraft** [comment]
This would include the projects in #120

**Comment by cwackerfuss** [comment]
You can configure the tailwind theme -- https://tailwindcss.com/docs/theme

let me know if you think it'd be a good idea to add this to the readme

**Comment by techpluscraft** [comment]
Yes that would be great @cwackerfuss i was thinking of something like the way dark mode is where you can specify the color in app.css
