### ISSUE TITLE
Less request more question for ${solution}

### ISSUE THREAD

**Issue by ericdrgn** [cwackerfuss/react-wordle#152]
**Describe the solution you'd like**
I am not an expert on react and so I am running up against a wall and can't figure out if what I want to do is even possible. 

In the strings file ${solution} places the word of the day in an alert so I tried to use it elsewhere but don't know if I can. I want to add it to the end of a url to provide users with quick access to a dictionary definition of the word that was used that day. For instance merriam websters url formats are pretty nice and you can just add the word you are looking for into the end of the url (https://www.merriam-webster.com/dictionary/test). 

I tried https://www.merriam-webster.com/dictionary/${solution} and even tried making a new string using ${solution}, importing that into the modal and attempting to use the string at the end of the url but it doesn't reem to work. I am attempting to get this added in the stats modal above the countdown so that it shows up when you win/lose the game.

Of course I would like to format the link as well so it shows up like "definition" instead of the whole link. I am capable of doing that but I was just trying to get the link to be dynamic first.

Anyway if anyone is willing to help, even if just to point me in the right direction I would appreciate it!

**Comment by cwackerfuss** [comment]
We can't currently do this but I'd like to add support for it too.

PS I think the merriam-webster example is funny -- isn't it pretty easy to notice the solution is in the URL?

**Comment by ericdrgn** [comment]
that's why it would only show up in the share menu when you complete a game, that part wouldn't be that hard to add. I currently have a link within that stats modal right above the countdown timer. It only shows up when you lose/win in a given day.

**Comment by cwackerfuss** [comment]
Oh now I understand what you're trying to do.

You should be able to add something like:
```
<a href={`https://www.merriam-webster.com/dictionary/${solution}](https://www.merriam-webster.com/dictionary/${solution}`} target="_blank">Go to definition</a>
```

to the share modal. Note you need to import `solution`

**Comment by ericdrgn** [comment]
Any idea what I'm doing wrong here? The build is failing

```
return (
    <BaseModal
      title={STATISTICS_TITLE}
      isOpen={isOpen}
      handleClose={handleClose}
    >
      <StatBar gameStats={gameStats} />
      <h4 className="text-lg leading-6 font-medium text-white dark:text-white">
        {GUESS_DISTRIBUTION_TEXT}
      </h4>
      <Histogram gameStats={gameStats} />
      {(isGameLost || isGameWon) && (
        <div className="mt-5 sm:mt-6 columns-2 dark:text-white">
          <div>
            <h5>{NEW_WORD_TEXT} <a href={`https://www.merriam-webster.com/dictionary/${solution}](https://www.merriam-webster.com/dictionary/${solution}`} target="_blank">Go to definition</a> </h5>
            <Countdown
              className="text-lg font-medium text-white dark:text-white"
              date={tomorrow}
              daysInHours={true}
            />
          </div>
          <button
            type="button"
            className="mt-2 w-full rounded-md border border-white shadow-sm px-4 py-2 bg-black text-base font-medium text-white hover:bg-black focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-black dark:border-white sm:text-sm"
            onClick={() => {
              shareStatus(guesses, isGameLost, isHardMode)
              handleShare()
            }}
          >
            {SHARE_TEXT}
          </button>
        </div>
      )}
    </BaseModal>
  )
}
```
I have solution imported with ``` import { solution } from './words' ```

**Comment by ericdrgn** [comment]
Oh sorry I did have a relevant error too, I'm getting ```Module not found: Error: Can't resolve './words' in '/opt/build/repo/src/components/modals'```

**Comment by ericdrgn** [comment]
sweet it's working! for anyone in the future the below is specifically for the stats modal above the countdown.

make sure at the top you import solution like so ``` import { solution } from '../../lib/words' ```

the code (I had to adjust slightly @cwackerfuss as what you sent is a broken link) is below 

```
  return (
    <BaseModal
      title={STATISTICS_TITLE}
      isOpen={isOpen}
      handleClose={handleClose}
    >
      <StatBar gameStats={gameStats} />
      <h4 className="text-lg leading-6 font-medium text-white dark:text-white">
        {GUESS_DISTRIBUTION_TEXT}
      </h4>
      <Histogram gameStats={gameStats} />
      {(isGameLost || isGameWon) && (
        <div className="mt-5 sm:mt-6 columns-2 dark:text-white">
          <div>
            <h5>{NEW_WORD_TEXT} <a href={`https://www.merriam-webster.com/dictionary/${solution}`} target="_blank" rel="noreferrer">go to definition</a> </h5>
            <Countdown
              className="text-lg font-medium text-white dark:text-white"
              date={tomorrow}
              daysInHours={true}
            />
          </div>
```
