### ISSUE TITLE
Question About Solutions 

### ISSUE THREAD

**Issue by lampy12** [cwackerfuss/react-wordle#153]
I was wondering if there is a way to not make it based on changing every 24 hours but you can just play whenever you like to with a new solution each time 👍

**Comment by cwackerfuss** [comment]
- You'd have to update the function here to randomly pick a number between `0` and `WORDS.length - 1` instead of getting it based on time
- You would have to do some light refactoring of the UI since there are references to the new word appearing on a daily interval

**Comment by jtraverso** [comment]
In https://www.wordle.cl I made it every 8 hours, my modifying words.ts:

export const getWordOfDay = () => {
  // January 1, 2022 Game Epoch
  const epochMs = new Date('January 1, 2022 00:00:00').valueOf()
  const now = Date.now() 
  const msInDay = 28800000 //modified to play every 8 hours (8*60*60*1000)
  const index = Math.floor((now - epochMs) / msInDay)
  const nextday = (index + 1) * msInDay + epochMs 

  return {
    solution: WORDS[index % WORDS.length].toUpperCase(),
    solutionIndex: index,
    tomorrow: nextday,
  }
}
