### ISSUE TITLE
Dockerized application is not working with prod image.

### ISSUE THREAD

**Issue by naeem-akhtar** [cwackerfuss/react-wordle#160]
**Describe the bug**
The production docker image is running on port 80 (default port of Nginx).
If we follow README then the docker image is supposed to run on port 3000 which is incorrect for prod image. Also, the line "EXPOSE 80" is also missing in Dockerfile for the prod stage.
README (and Dockerfile) should be updated to reflect the correct port and steps about the production image.

**To Reproduce**
1. Build production docker image `docker build -t game . --target=prod`
2. Start docker container `docker run -d -p 3000:3000 game`
3. Application not accessible in the browser at `http://localhost:3000/` or `http://localhost:80/`

**Expected behavior**
The application should be running and accessible on the browser at `http://localhost/` or `http://localhost:80/`.

Please let me know and I will raise a PR to update the readme and Dockerfile.

**Comment by cwackerfuss** [comment]
Hi @naeem-akhtar -- we recently merged this PR: https://github.com/cwackerfuss/react-wordle/pull/161

Can you try pulling and see if that helps?

**Comment by naeem-akhtar** [comment]
I have raised a PR that will add proper instruction for building and running docker containers for both development and production env.
Hope that will help others while using docker images.
