### ISSUE TITLE
How To Play modal should open on first visit

### ISSUE THREAD

**Issue by diondiondion** [cwackerfuss/react-wordle#163]
**Is your feature request related to a problem? Please describe.**

Users new to the game need to press the info icon to find instructions on how to play.

**Describe the solution you'd like**

The first time the game is opened, the How to play modal should be opened. It should not be shown to returning users.

**Describe alternatives you've considered**

If the instructions weren't hidden behind an icon with no text label, the lack of automatically opened instructions probably wouldn't be an issue.

**Additional context**

This is also how it's handled in the original game.

**Comment by cwackerfuss** [comment]
Fixed now @diondiondion. Thanks for nudging us on this!

**Comment by diondiondion** [comment]
Thanks! 🙏
