### ISSUE TITLE
Move "About this game" into a menu

### ISSUE THREAD

**Issue by gheja** [cwackerfuss/react-wordle#167]
The "About this game" button is off screen by default. As there is no scroll bar visible it is not really intuitive to search for content below the game screen. Also, it feels unexpected to scroll a part of the game area off screen.

Is this issue only visible on my phone's resolution?

Maybe the button should be moved into a modal, like "How To Play" or "Settings".

I can implement it if you'd like, I just need some guidance.

**Comment by diondiondion** [comment]
I think it would make sense to move that link into the how to play pop-up.

**Comment by cwackerfuss** [comment]
@gheja @diondiondion I just posted a PR to address this (linked above). Thanks

**Comment by gheja** [comment]
Looks great!
