### ISSUE TITLE
Bug - syscordle

Some of the 5 letter word syscalls contain numbers (like today's syscall). There is no way to enter a digit via the UI.

### ISSUE THREAD

**Issue by aTOz132** [cwackerfuss/react-wordle#177]

**Comment by TheKnowles** [comment]
Wouldn't this need to be inplemented by the downstream implementation?

**Comment by cwackerfuss** [comment]
Indeed - from the looks of it based on the url of Syscordle (https://nezza.github.io/syscordle/), you can reach out to this user if you'd like to let them know: https://github.com/nezza
