### ISSUE TITLE
Allow to go back in time to do older words

### ISSUE THREAD

**Issue by Th0masL** [cwackerfuss/react-wordle#178]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to go back in time to do words of past days.

**Describe the solution you'd like**
I guess we could add a button to switch the date.

**Describe alternatives you've considered**
For now I'm using other non open source app that allow that.

**Comment by cwackerfuss** [comment]
This has been mentioned before and I think it's a very good idea. We'll come up with a good way to do this but it requires a bit of work, should get around to this within the next few weeks.

**Comment by gheja** [comment]
I think a new modal with a calendar would be nice, with the days colored to show which days were solved (or lost). Also, adding the option to re-play a day (except for today?) would be useful.

Also, it must be noted that if this gets implemented the wordlist has to be fixed up to at least the current date - adding a test for this in the build process might be the best to guarantee this.

**Comment by muhelen** [comment]
Any new updates to this feature? Old word Archive would be a great idea.
