### ISSUE TITLE
Hard to use on mobiles with small screens

### ISSUE THREAD

**Issue by oradwell** [cwackerfuss/react-wordle#188]
**Describe the bug**
Need to scroll on iPhone's with small screens

**To Reproduce**
Open the page on iPhone SE (2020)

**Expected behavior**
The whole screen should be utilised, and there should be no empty space

**Screenshots**
![Screenshot from 2022-02-13 21-06-45](https://user-images.githubusercontent.com/5054896/153775116-777654ba-44dc-4c6b-9798-810303fdd64f.png)
![Screenshot from 2022-02-13 21-11-05](https://user-images.githubusercontent.com/5054896/153775210-eda5f4f7-faeb-4c05-ae0f-114012e13619.png)

**Smartphone:**
 - Device: iPhone SE (2020)
 - OS: v13.4
 - Browser: Safari

**Additional context**
We should resize the elements on the page to fit them on all screen sizes.

**Comment by candardo** [comment]
I get the same behaviour on Android 12 with "large text" accessibility setting on:

- in webview
- on Firefox either using system accessibility setting or its own zoom text setting

No issue on Chrome.

**Comment by oradwell** [comment]
this is fixed by #209
