### ISSUE TITLE
max challenges variable is hard coded in share text

### ISSUE THREAD

**Issue by joedel263** [cwackerfuss/react-wordle#190]
Super minor, is a really simple fix for anyone using the code (edit src\lib\share.ts) but throwing it out there for the sake of completion.

MAX_CHALLENGES in src\constants\settings.ts is used to determine how many guesses someone has per game.  changing it works as expected, but the share text always reads x of 6 guesses as the 6 is hard coded and not pulling from the variable.

**Comment by cwackerfuss** [comment]
Thanks for reporting @joedel263 -- just put up a PR addressing this.
