### ISSUE TITLE
Downstream: Rows should be more responsible

### ISSUE THREAD

**Issue by lens0021** [cwackerfuss/react-wordle#195]
**Describe the bug**
If one row has many cells, some cells overflow the screen.

**To Reproduce**
1. Set `MAX_WORD_LENGTH` to a larger number.
2. Change `VALID_GUESSES` to a suitable one.
3. Start the game.
3. Type a long word.

**Expected behavior**
All letters of the given word should be visible.

**Screenshots**
The below game has a flexible word length.
![image](https://user-images.githubusercontent.com/28209361/153807938-f2f7c4d9-2e66-496a-9cf8-257139efeb01.png)

**Additional context**
The original issue: https://github.com/han-dle/pocketmon/issues/9

**Comment by cwackerfuss** [comment]
Those rows are quite long! I'm concerned that solving for this is not going to be worth the extra code complexity for the majority of usecases, so I'm thinking we leave this behavior how it is in the opensource repo and this can be something you'd solve for in a fork if needed.

That being said, I'm open to supporting this if others think it's worthwhile..
