### ISSUE TITLE
Share button does not work (iPhone6, Safari, iOS 12.5.5) + hints for solution

### ISSUE THREAD

**Issue by pietroppeter** [cwackerfuss/react-wordle#206]
**Describe the bug**

Share button does not copy results. I know this has been reported multiple times and ascribed to HTTP (#94 and #43) but I think I have new elements and a possible hint for a solution, see below in context ("To Reproduce" and "Expected behavior" can be skipped).

**To Reproduce**

1. solve the puzzle
2. click share
3. no modal for share successful appears
4. pasting in a chat or elsewhere does not paste the correct result

The behavior was found with an iPhone 6 (iOS 12.5.5) using Safari 

**Expected behavior**

3. modal confirm copying to clipboard should appear
4. pasting should paste the correct result

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: 12.5.5
 - Browser safari
 - Version ?

phone was not mine but I was able to confirm the issue

**Additional context**

I am starting to port my Italian version (born on Jan 3rd, same day when this clone was born) from the usage of original world files (which are not licensed open source) to use this clone. My current italian version is here (not relevant for this): https://github.com/pietroppeter/wordle-it 

I have set up a new version (translation ongoing): https://github.com/par-le/react-wordle

There is another italian version (parolette) which is based on an earlier version of this clone: https://github.com/xho/parolette
That version was forked before share was implemented and so share was implemented in a different way. **I can confirm that with the above mentioned phone/os/browser sharing with parolette works, while (as mentioned) it does not work with this clone**.

It seems to me the difference resides in [this line](https://github.com/xho/parolette/blob/d22f3d6541056abf6b9caf38eeaa54491700a75b/src/components/elements/ShareButton.tsx#L41) which offers an alternative share mechanism compared with [what is currently implemented](https://github.com/cwackerfuss/react-wordle/blob/5660d14f199675ae147eb601f21c8ec733a76ef3/src/lib/share.ts#L11) here.

I will try to make the share approach of parolette work with the current version of this clone, but since I have never coded in typescript that might take me a moment (if anyone wants to give pointers happy to take them :)).

Thanks for the great work on this and have a good day.

**Comment by cwackerfuss** [comment]
Hey @pietroppeter thanks for reporting. Can you try the share functionality from this link?

https://react-wordle-git-fork-igitur-implement-share-api-cwackerfuss.vercel.app/

That is the deployed feature branch for this pull request, which may fix the issue once its merged: https://github.com/cwackerfuss/react-wordle/pull/182

**Comment by pietroppeter** [comment]
Ah nice, did not see there was already a PR with the fix, looks good, yes I will try and report back!

**Comment by pietroppeter** [comment]
Ok, I heard from my tester and unfortunately the current state of the PR above does not fix it for them. :/

**Comment by pietroppeter** [comment]
I do not think this was closed by recent PRs but I will (ask to) test again (using the live demo of the repo, I guess) and let you know. In case this is still not fixed I will reopen.

**Comment by igitur** [comment]
Yes, Sorry, I accidentally marked #289 as closing #206. Got a bit confused. In any case, there's not much more I can do on this. I don't have access to an iPhone 6. Someone else with the means will have to address this.

**Comment by pietroppeter** [comment]
Yep, no problem. I know it is not practical, I have a single friend with this issue and if she changes the phone I will not be able to test it either :)

I was able to confirm the issue is still present so I will reopen this.

Anyway in this issue I mentioned the fact that an Italian version (parolette) does not suffer from this issue and the code is available (linked above). At some point I want to try to adapt that code on this version but since typescript is not really my thing it will not be straightfoward for me (and time, alas, is always scarce).

**Comment by pietroppeter** [comment]
mmh, it appears I cannot reopen this, can someone do this for me?
