### ISSUE TITLE
Share button issues

### ISSUE THREAD

**Issue by hooray4me** [cwackerfuss/react-wordle#217]
**Describe the bug**
The share button is not working when testing in Chrome.

**To Reproduce**
1. Play game
2. Click on click on share

**Expected behavior**
Copy share info to clipboard.

**Screenshots**
![image](https://user-images.githubusercontent.com/12399138/154362913-2655512d-aba7-435b-b7a4-c06fecc3886d.png)
![image](https://user-images.githubusercontent.com/12399138/154363027-f0dcce16-e150-4c15-aa2c-fde2a7638154.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Chrome

**Additional context**
![image](https://user-images.githubusercontent.com/12399138/154363189-3cec90f1-9136-40ca-9a47-5982fd736dbf.png)

**Comment by hooray4me** [comment]
Any thoughts on this?

**Comment by hooray4me** [comment]
Solved on my own... turns out local storage won't work incognito... duh :)

**Comment by gheja** [comment]
Good to know! Thanks for sharing the solution.
