### ISSUE TITLE
Harder mode (feature suggestion)

### ISSUE THREAD

**Issue by gheja** [cwackerfuss/react-wordle#218]
An even harder mode where the "present" clue is enforced more strictly, the guess must not contain the letter in the position that led to a "present but not here" before.

**Comment by pietroppeter** [comment]
relevant tweet by Josh Wardle on this harder mode: https://twitter.com/powerlanguish/status/1479226926636089347?s=20&t=SlTr_5kspXEQCTA53M_cag

> knowing what I know now, I might go with your interpretation instead

**Comment by gheja** [comment]
Thanks! Yes, adding a "you can't use the \"absent\" letters" rule would be great, too.

And I must admit I forgot that I played earlier by this custom rule as well - to increase the efficiency, but still I finished with 4 or 5 guesses mostly.

**Comment by cwackerfuss** [comment]
@gheja for me, this feels like one of those features that, since it isn't in the OG wordle, probably best to not include it in the core project here. Thoughts?

I wish there was a clean way to include these "optional" features in the build. Maybe we need to build a scaffolding/generator cli tool... :D

**Comment by gheja** [comment]
I'm on the fence, I'd suggest this as an optional feature so it would not affect the game play by default.

But again, every new (even optional) feature would make testing more and more complicated, the codebase more prone to accidental errors.

I'd totally agree if you discarded this, defining the scope and focusing on that is important, and this is definitely not part of the OG Wordle. On these lines, I'd discard it too.

p.s. I really need to start playing with the automated tests :)
