### ISSUE TITLE
Variable length words in same docker container

### ISSUE THREAD

**Issue by hooray4me** [cwackerfuss/react-wordle#234]
Would it be possible to have some kind of array of words, say a list of 4, 5, 6 and 7 character words, and the list be chosen at random the next day?
Right now I have have a docker image for each character length of word from 4 to 12 characters. I script stopping the docker container at midnight and starting a different one in its place. From the external perspective (behind nginx) their progress data is still saved. This works but is ugly. Would love to find a solution in a single docker image.

**Comment by JuanFontes** [comment]
Hi @hooray4me I sent a PR that does what you are looking for, I guess. https://github.com/cwackerfuss/react-wordle/pull/229 -- We can have different words, no matter what's the size.

**Comment by hooray4me** [comment]
@JuanFontes how are you handling the different length guess words?

**Comment by hooray4me** [comment]
I'll try combining all possible guess words of various lengths and see what happens

**Comment by hooray4me** [comment]
Thanks for this! solution length was exactly what I needed! Now I have a very large validGuesses but it had no problem building. :)

**Comment by hooray4me** [comment]
@JuanFontes , or anyone else... Any Idea how to handle re-calculating the proper spacing for the game title and buttons? 
![image](https://user-images.githubusercontent.com/12399138/154862192-6656b8a5-dba9-4f85-9862-c43ad7a6bc2f.png)

**Comment by cwackerfuss** [comment]
After a few different discussions here and having more time to think about this dynamic guess length idea, I don't believe we should implement this in the core OS project. The reality is that if someone is making their own fork of this, there are a few code things you have to do. When changing the word length, we enumerate the steps [in the README already](https://github.com/cwackerfuss/react-wordle#how-can-i-change-the-length-of-a-guess). Making this dynamic makes the code more complex to support a situation that likely only applies to a small subset of forks. It is worth noting that the current implementation is intentionally and thoughtfully built with "variable word length" in mind, but you are correct that it doesn't really support variable word-lengths from day-to-day.

**Comment by cwackerfuss** [comment]
Apologies - reopening in case there is further discussion. 😄

**Comment by hooray4me** [comment]
This is working brilliantly after attempting what we've talked about, in my fork.

Sent via the Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by IbMxCipHERgodDEsS** [comment]
Yall still whack ass all hell.

**Comment by hooray4me** [comment]
lol. Its hard to explain. Nutshell we run a fansite for a SiriusmXM radio show https://bearsarefast.com ... we've made this into a wordgame for this show based off of the stupid things the producer says (tylerisms). this is the result of our stupid endeavors lol https://tylerdle.com

Sent via the Outlook for Android<https://aka.ms/ghei36>
________________________________
