### ISSUE TITLE
Character problem in words like "ç" and "i"

### ISSUE THREAD

**Issue by Cryptoseen** [cwackerfuss/react-wordle#239]
I'm just learning coding for hobby purposes. I get an error when I replace all of the wordlist.ts with Turkish words containing Turkish letters such as ç,i and build it. If I change only today's word in wordlist.ts, it builds and there is no problem. But this time, if it is a Turkish word with the letter i or ç in it, I need to use it like I or C in English. When I try with ç and i it gives the error word not found. Where am I doing wrong?

**Additional context**

**Comment by gheja** [comment]
The code [checks for exact matches](https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L6-L15) so you need to update [the keyboard](https://github.com/cwackerfuss/react-wordle/blob/main/src/components/keyboard/Keyboard.tsx) to have those specific keys.

**Comment by Cryptoseen** [comment]
> The code [checks for exact matches](https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L6-L15) so you need to update [the keyboard](https://github.com/cwackerfuss/react-wordle/blob/main/src/components/keyboard/Keyboard.tsx) to have those specific keys.

https://imgur.com/bU9UTN8   This is how I added the special characters in the beginning. When I add words containing Turkish language to the Wordlist file and compile, I get the following error:

    'Words' are not exported from '../constants/wordlist' (imported as 'Words').


But the wordlist file remains original and when I just change the word of the day the compilation doesn't give an error. But at that time I am getting "word not found error" for word containing letters ç and i. There is no problem with Turkish characters like "ş".

**Comment by gheja** [comment]
I have added a few dummy words with the letters you provided ('aaaaç' 'aaaai' 'aaaaş'), updated the keyboard and it works for me.

Could you check the patch below?

![image](https://user-images.githubusercontent.com/1894642/154814036-8f257246-858e-4320-a733-21161bf6dca9.png)

```patch
diff --git a/src/components/keyboard/Keyboard.tsx b/src/components/keyboard/Keyboard.tsx
index 485e8b3..bb88e9b 100644
--- a/src/components/keyboard/Keyboard.tsx
+++ b/src/components/keyboard/Keyboard.tsx
@@ -77,7 +77,7 @@ export const Keyboard = ({
         <Key width={65.4} value="ENTER" onClick={onClick}>
           {ENTER_TEXT}
         </Key>
-        {['Z', 'X', 'C', 'V', 'B', 'N', 'M'].map((key) => (
+        {['Z', 'X', 'C', 'V', 'Ş', 'I', 'Ç'].map((key) => (
           <Key
             value={key}
             key={key}
diff --git a/src/constants/wordlist.ts b/src/constants/wordlist.ts
index 2bafd57..172090f 100644
--- a/src/constants/wordlist.ts
+++ b/src/constants/wordlist.ts
@@ -1,4 +1,7 @@
 export const WORDS = [
+  'aaaaç',
+  'aaaai',
+  'aaaaş',
   'which',
   'there',
   'their',
```

**Comment by joedel263** [comment]
I built a Turkish version.  The issue with I is that on an American keyboard the lowercase i is one letter while the uppercase I is another so when the script is converting to upper/lower case it's seeing/using the wrong thing.  I did not see an issue with Ç

The solution I found was to update the way the script was converting case "toLocaleUpperCase('tr-TR')" in Keyboard.tsx and "toLocaleLowerCase('tr-TR')" in Words.ts

if you want to also be able to use an actual keyboard to enter the local letters (instead of the screen) you also have to update what the to uppercase is reacting to in Keyboard.tsx (as by default it's only A through Z)

I'm not well versed enough in github to share my code, but am happy to help.

**Comment by Cryptoseen** [comment]
> I built a Turkish version. The issue with I is that in Turkish on an American keyboard the lowercase i is one letter while the uppercase I is another so when the script is converting to upper/lower case it's seeing/using the wrong thing. I did not see an issue with Ç
> 
> The solution I found was to update the way the script was converting case "toLocaleUpperCase('tr-TR')" in Keyboard.tsx and "toLocaleLowerCase('tr-TR')" in Words.ts
> 
> if you want to also be able to use an actual keyboard to enter the local letters (instead of the screen) you also have to update what the to uppercase is reacting to in Keyboard.tsx (as by default it's only A through Z)
> 
> I'm not well versed enough in github to share my code, but am happy to help.

I tried, it happens with some words, but as seen in the example, this word gives an error not found in words such as "CİBİN" or "MALIÇ". This is because there is no capital letter İ in english but I don't know how to fix it.

**Comment by Cryptoseen** [comment]
> I have added a few dummy words with the letters you provided ('aaaaç' 'aaaai' 'aaaaş'), updated the keyboard and it works for me.
> 
> Could you check the patch below?
> 
> ![image](https://user-images.githubusercontent.com/1894642/154814036-8f257246-858e-4320-a733-21161bf6dca9.png)
> 
> ```diff
> diff --git a/src/components/keyboard/Keyboard.tsx b/src/components/keyboard/Keyboard.tsx
> index 485e8b3..bb88e9b 100644
> --- a/src/components/keyboard/Keyboard.tsx
> +++ b/src/components/keyboard/Keyboard.tsx
> @@ -77,7 +77,7 @@ export const Keyboard = ({
>          <Key width={65.4} value="ENTER" onClick={onClick}>
>            {ENTER_TEXT}
>          </Key>
> -        {['Z', 'X', 'C', 'V', 'B', 'N', 'M'].map((key) => (
> +        {['Z', 'X', 'C', 'V', 'Ş', 'I', 'Ç'].map((key) => (
>            <Key
>              value={key}
>              key={key}
> diff --git a/src/constants/wordlist.ts b/src/constants/wordlist.ts
> index 2bafd57..172090f 100644
> --- a/src/constants/wordlist.ts
> +++ b/src/constants/wordlist.ts
> @@ -1,4 +1,7 @@
>  export const WORDS = [
> +  'aaaaç',
> +  'aaaai',
> +  'aaaaş',
>    'which',
>    'there',
>    'their',
> ```
> 
> Edit: pushed the changes to a branch here: https://github.com/gheja/react-wordle/tree/issue-239-test


https://imgur.com/a/1REVqY0
I tried, it happens with some words, but as seen in the example, this word gives an error not found in words such as "CİBİN" or "MALIÇ". This is because there is no capital letter İ in english but I don't know how to fix it.

**Comment by Cryptoseen** [comment]
> I built a Turkish version. The issue with I is that in Turkish on an American keyboard the lowercase i is one letter while the uppercase I is another so when the script is converting to upper/lower case it's seeing/using the wrong thing. I did not see an issue with Ç
> 
> The solution I found was to update the way the script was converting case "toLocaleUpperCase('tr-TR')" in Keyboard.tsx and "toLocaleLowerCase('tr-TR')" in Words.ts
> 
> if you want to also be able to use an actual keyboard to enter the local letters (instead of the screen) you also have to update what the to uppercase is reacting to in Keyboard.tsx (as by default it's only A through Z)
> 
> I'm not well versed enough in github to share my code, but am happy to help.

Yes, I thought the letter "ç" was the source of the problem, but now I understand that it gives this error because English does not have a capital letter "I". Is it possible for you to share the code, I'm not a professional software developer, I'm just trying to learn

**Comment by joedel263** [comment]
in src/components/Keyboard/Keyboard.tsx
change line 40
from      const key = e.key.toUpperCase()
to        const key = e.key.toLocaleUpperCase('tr-TR')

in src/lib/words.ts
change lines 8 and 9
from
    WORDS.includes(word.toLowerCase()) ||
    VALID_GUESSES.includes(word.toLowerCase())
to
    WORDS.includes(word.toLocaleLowerCase('tr-TR')) ||
    VALID_GUESSES.includes(word.toLocaleLowerCase('tr-TR'))

if you want a physical keyboard to work you will need to edit  src/components/Keyboard/Keyboard.tsx to include the alternate characters as it presently only compares A through Z (the specific code is lines 41 and 42)
adding the following three lines after line 43 (before line 44) will quickly fix just the İ (that's all I did for the moment because my game has an audience of one)

        if (key.length === 1 && key === 'İ') {
          onChar(key)
        }
 
I actually don't even speak Turkish, I have a friend who is from Turkey who wanted a word game, and it's been an amazing learning experience.

**Comment by Cryptoseen** [comment]
> if (key.length === 1 && key === 'İ') {
>           onChar(key)
>         }

Yes, that solved the problem, thank you very much.  ☺ ☺ ☺

**Comment by Cryptoseen** [comment]
> in src/components/Keyboard/Keyboard.tsx change line 40 from `const key = e.key.toUpperCase()` to `const key = e.key.toLocaleUpperCase('tr-TR')`
> 
> in src/lib/words.ts change lines 8 and 9 from
> 
> ```
>     WORDS.includes(word.toLowerCase()) ||
>     VALID_GUESSES.includes(word.toLowerCase())
> ```
> 
> to
> 
> ```
>     WORDS.includes(word.toLocaleLowerCase('tr-TR')) ||
>     VALID_GUESSES.includes(word.toLocaleLowerCase('tr-TR'))
> ```
> 
> if you want a physical keyboard to work you will need to edit src/components/Keyboard/Keyboard.tsx to include the alternate characters as it presently only compares A through Z (the specific code is lines 41 and 42) adding the following three lines after line 43 (before line 44) will quickly fix just the İ (that's all I did for the moment because my game has an audience of one)
> 
> ```
>         if (key.length === 1 && key === 'İ') {
>           onChar(key)
>         }
> ```
> 
> I actually don't even speak Turkish, I have a friend who is from Turkey who wanted a word game, and it's been an amazing learning experience.

Yes, that solved the problem, thank you very much.  ☺ ☺ ☺

**Comment by Cryptoseen** [comment]
@gheja Thank you so much. ☺ ☺ ☺
Also, I'm not closing the issue because there might be a different method. because my goal is to learn. Thank you very much to everyone who helped.

**Comment by Cryptoseen** [comment]
@gheja Thank you so much.  ☺ ☺ ☺
Also, I'm not closing the issue because there might be a different method. because my goal is to learn. Thank you very much to everyone who helped.

**Comment by Cryptoseen** [comment]
> > in src/components/Keyboard/Keyboard.tsx change line 40 from `const key = e.key.toUpperCase()` to `const key = e.key.toLocaleUpperCase('tr-TR')`
> > in src/lib/words.ts change lines 8 and 9 from
> > ```
> >     WORDS.includes(word.toLowerCase()) ||
> >     VALID_GUESSES.includes(word.toLowerCase())
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to
> > ```
> >     WORDS.includes(word.toLocaleLowerCase('tr-TR')) ||
> >     VALID_GUESSES.includes(word.toLocaleLowerCase('tr-TR'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > if you want a physical keyboard to work you will need to edit src/components/Keyboard/Keyboard.tsx to include the alternate characters as it presently only compares A through Z (the specific code is lines 41 and 42) adding the following three lines after line 43 (before line 44) will quickly fix just the İ (that's all I did for the moment because my game has an audience of one)
> > ```
> >         if (key.length === 1 && key === 'İ') {
> >           onChar(key)
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I actually don't even speak Turkish, I have a friend who is from Turkey who wanted a word game, and it's been an amazing learning experience.
> 
> Yes, that solved the problem, thank you very much. ☺ ☺ ☺

I said the problem is solved, but there is a problem, for example, the Turkish word "TABİİ" was added to the wordlist file as "tabii". And when I type "TABİİ" while playing games, it accepts the letters "i" incorrectly. and when 5 words are guessed and the game is over, it gives an error that the word is "TABII".

**Comment by gheja** [comment]
Thank you @joedel263, I was thinking about similar method, I think I will make a PR with a configuration parameter to use either the `toLowerCase()` or the `toLocaleLowerCase()` with custom locale (same for upper).

> if you want a physical keyboard to work you will need to edit src/components/Keyboard/Keyboard.tsx

That's correct, you need to edit the keyboard if you'd like to have non-english characters.

> it's been an amazing learning experience

I agree! It might be frustating at first that one solution does not fit all but looking into the problem, understanding and then coming up with a solution is great. (Or fidning a library of someone who solved it before and kind enough to share.)

I will take a look into the "tabii" vs. "TABİİ".

**Comment by gheja** [comment]
> I will take a look into the "tabii" vs. "TABİİ".

I believe a `toUpperCase()` was not replaced [here](https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L63) or the solution was already stored in localstorage. Could you check it?

**Comment by joedel263** [comment]
> > I will take a look into the "tabii" vs. "TABİİ".
> 
> I believe a `toUpperCase()` was not replaced [here](https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L63) or the solution was already stored in localstorage. Could you check it, clear localstorage and give one more try?

that one's on me, I completely missed it earlier when looking at my code edits. next I need to learn how github works so I can better support the community. 

my version is running here https://test.joedle.com (until my friend gives it a name for a domain name) if that helps any.

**Comment by Cryptoseen** [comment]
> > I will take a look into the "tabii" vs. "TABİİ".
> 
> I believe a `toUpperCase()` was not replaced [here](https://github.com/cwackerfuss/react-wordle/blob/main/src/lib/words.ts#L63) or the solution was already stored in localstorage. Could you check it, clear localstorage and give one more try?

https://imgur.com/a/za3uwr4 

I cleaned and rebuilt Local storage via Netlify.
and I entered the following code:
 
solution: WORDS[index % WORDS.length].toLowerCase(),

but the problem is still not solved.

**Comment by gheja** [comment]
I think you'd need this:
```javascript
solution: WORDS[index % WORDS.length].toLocaleUpperCase('tr-TR'),
```

**Comment by Cryptoseen** [comment]
> ```js
> solution: WORDS[index % WORDS.length].toLocaleUpperCase('tr-TR'),
> ```

https://imgur.com/a/cWkcqxd 

it worked. You have been so helpful ☺ ☺ ☺

**Comment by gheja** [comment]
I am glad it works now :)

I have created a pull request with the changes: #242

Thanks for your help and tests!

**Comment by Cryptoseen** [comment]
> I am glad it works now :)
> 
> I have created a pull request with the changes: #242
> 
> Thanks for your help and tests!

Thanks to you and @joedel263 otherwise I'm like a baby just learning to walk in coding.  :)

**Comment by gheja** [comment]
You are doing great, keep working on it! :)

**Comment by Cryptoseen** [comment]
> You are doing great, keep working on it! :)

It will be a very stupid question, but env. What should we write for the Turkish "İ" in front of the REACT_APP_LOCALE_STRING= file? Maybe it's too simple but I wrote "toLocaleUpperCase()" and it didn't work. "toLocaleLowerCase()" didn't work either. I added ('tr-TR') still didn't work.  :( @gheja

**Comment by gheja** [comment]
I think you need simply 'tr-TR'. I'll update the readme.

**Comment by Cryptoseen** [comment]
('tr-TR') I tried this way. It built it but it didn't work, there was only a white page :)  and now i wrote without parentheses. actually very simple but not just for me :)
