### ISSUE TITLE
Autofill and Lock Correct Letters in Hard Mode

### ISSUE THREAD

**Issue by ericdrgn** [cwackerfuss/react-wordle#245]
**Is your feature request related to a problem? Please describe.**
Is there a way to autofill the current row with fully correct letters and lock them at the same time if you are in hard mode? So if you made a guess and found out that for the guess TESTS the T, E, and T were all in the correct spots the current row would autofill with those and lock them in place. So all a user could type in would be for the two blanks that are left in the word.

My reasoning for this is is makes it far more intuitive in hard mode as a user has to place those letters there anyway but instead of putting in lots of thought and doing it wrong (getting the "T needs to be in position 1" message) it just prevents you from doing it at all by already having the fully correct letters filled in.

**Comment by Nicolasmartinsimon** [comment]
Greater

**Comment by cwackerfuss** [comment]
I agree its a little weird... but, without actually building this and testing it out, my intuition is that the UX behavior around how to add/delete new characters would be a little strange. For this reason, plus the fact that the OG version doesn't do this, this functionality is not something I feel we should add to the core OS project. Thank you for the suggestion.
