### ISSUE TITLE
Zfztgihhu

### ISSUE THREAD

**Issue by Nicolasmartinsimon** [cwackerfuss/react-wordle#251]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Nicolasmartinsimon** [comment]
Nice one

**Comment by gheja** [comment]
@cwackerfuss, don't you want to ban this guy?

**Comment by cwackerfuss** [comment]
Blocked this user thanks @gheja
