### ISSUE TITLE
Unicode Characters Keyboard > Different Keys on keypress

### ISSUE THREAD

**Issue by muhelen** [cwackerfuss/react-wordle#253]
While integrating Tamil unicode characters #203 into the keyboard, I've to load a new compound letter ((letter+modifier) keys to display on the keyboard as there are total of 247 Tamil characters to display in full.
 
For an example the current key **க** on the keyboard need to change and show as **கா** when pressing with **ா** key. 
### க+ ா=கா

Here the existing key showing the vowel and consonant keys
<img width="509" alt="Screenshot 2022-02-21 at பிற்பகல் 4 54 15" src="https://user-images.githubusercontent.com/5513469/154921006-ec46e6cf-fb50-4cda-a4a0-800baa00326b.png">

Here the wanted keys showing the new compound letters (vowel + consonant)
<img width="510" alt="Screenshot 2022-02-21 at பிற்பகல் 4 54 03" src="https://user-images.githubusercontent.com/5513469/154920991-3abb321d-b1c6-4d3f-b9fc-fc8b03685904.png">

I've almost make it work on my [fork](https://github.com/omtamil/soladle) , but unable to find the exact key press functions to include.

@gheja Could you help into this as well?

**Comment by gheja** [comment]
I am not sure if I understand it correcty, please correct me if needed. As I understand you would like to change the letters on the game's keyboard when a key on your physical keyboard is pressed.

In this case there is a need for a custom function that listens for the `keydown` and `keyup` events and checks the correct key then walks through the keys (the `<button>` elements) and replaces their `innerHTML` properties.

**Comment by muhelen** [comment]
@gheja Yes, I’ve already done the toggle version of the keyboard, when pressed the consonants key it will activate and show the the modifier keyboards. The issue I’m facing here is the Unicode keys not displaying it correctly. If you look at my keyboard.tsx file from my fork you could understand the error I’m referring to..

**Comment by muhelen** [comment]
Yes, I've done the toggle version to solve this issue and the easiest solution to implement. Thanks @gheja for your suggestions.
