### ISSUE TITLE
Install via FTP?

### ISSUE THREAD

**Issue by benny148** [cwackerfuss/react-wordle#264]
I'm trying to install this via FTP but I'm not having much luck...I've downloaded the .zip, unzipped, and uploaded the files to the public_html folder.  Is there something I'm missing? Thanks for the help

**Comment by gheja** [comment]
First you need to build it on a machine: after downloading and extracting the zip run the following:
```bash
cd react-wordle
npm install
npm run build
```

After this finishes you'll have a `build` directory. Copy the contents of it (not the directory itself) to `public_html` on your FTP.
