### ISSUE TITLE
Reduce download size by compressing wordlist

### ISSUE THREAD

**Issue by rbrignall** [cwackerfuss/react-wordle#266]
**Is your feature request related to a problem? Please describe.**
The main js bundle is around 360kb in size, which is significant, and a major factor in my decision not to use this version for Byrdle: I have ~50k users/day, meaning the daily bandwidth would be around 17 GB/day.   

**Describe the solution you'd like**
100kb of the js bundle is the list of permitted guesses, but you can (at least) halve that using a few simple tricks:
- Store the list as a single string (removes quotation marks and commas: 37.5% saving) and chop into 5-letter chunks after deployment
- Divide the list into 26 arrays, based on starting letter, and remove the starting letter (another 20% saving, after doing the first suggestion).

**Describe alternatives you've considered**
You could go further by changing encodings, but the above (which I use in my [deployed code](https://github.com/rbrignall/open-byrdle/blob/main/src/words_5_6.ts)) doesn't have a major impact on serving the page. 

Another option would be to use a Trie. I havne't investigated that.

**Additional context**
Here is the (Svelte) [wordlist](https://github.com/rbrignall/open-byrdle/blob/main/src/words_5_6.ts) that I use, including the code that recovers the array of words. As you can see, I can deploy 5- and 6-letter words in less than the original 5-letter array...

**Comment by gheja** [comment]
Speaking as a contributor, not the owner.

I think complicating things to compress the files in code is not really in the scope of this project.

Also, most webservers handle on-the-fly gzip/deflate compression which is optimal for text, [Nginx](https://docs.nginx.com/nginx/admin-guide/web-server/compression/), [Apache](https://httpd.apache.org/docs/2.4/mod/mod_deflate.html) can handle them with minimal configuration changes, and as it's all static content you could also use use a CDN provider like [CloudFlare](https://www.cloudflare.com/plans/free/) to cache all the files.

**Comment by JuanFontes** [comment]
Hi @rbrignall , I sent a suggestion doing what @gheja explained, but unfortunately, no one said anything. I put an example there, enabling gzip reduced almost 70% of the download size from the server. Let me know if you need some help on this.

**Comment by cwackerfuss** [comment]
Thanks @rbrignall ! It's good to hear that not having first-class support for compression was a major decision for you not deciding to use this project. I recognize not everyone has the technical ability to add compression themselves so this is something worth exploring.

@JuanFontes you posted https://github.com/cwackerfuss/react-wordle/issues/216 11 days ago, and closed it after a week. This is an open source project not our fulltime job so please have some patience!

A PR into this project that adds a few lines to the docker deployment instructions would be very welcome, please feel free to post one and we can take a look!

**Comment by JuanFontes** [comment]
Oh @cwackerfuss sorry for that, I didn't that I was impatient.. I completely understand that everyone here has their jobs and etc. I was just like: Ah no one said anything, neither in "Cool". So in my mind, it wasn't a good feature.

My bad, I'll reopen the issue @cwackerfuss !

**Comment by igitur** [comment]
Not really relevant to this issue, but it's good to see another choral enthusiast here :-)

**Comment by oradwell** [comment]
I've done something similar on Jazle (guessing JavaScript libraries)
https://github.com/oradwell/jazle/blob/main/Dockerfile.prod

**Comment by ryanlovallo** [comment]
I've done something similar as mentioned in the issue description, reducing the size of the wordlist from 139kb to 52kb.
