### ISSUE TITLE
Add: Wordle-Thai uses this source

### ISSUE THREAD

**Issue by underlines** [cwackerfuss/react-wordle#270]
Sorry, I can't make a pull request.

The following project also uses this source for Wordle-Thai:

https://buddhistuniversity.net/wordle-thai/

**Comment by muhelen** [comment]
@underlines Thanks for the add. While I don’t recognize any Thai characters, I’ve noticed you’ve implemented additional  blue button for vowel/letter. May I know how it works ?

**Comment by cwackerfuss** [comment]
Done
