### ISSUE TITLE
How to add a background image?

### ISSUE THREAD

**Issue by Kibris10** [cwackerfuss/react-wordle#271]
how would I go about adding a background image (if its possible), thanks!

**Comment by TheKnowles** [comment]
You can add a custom background image to tailwind.config.js:

```
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      backgroundImage: {
        'cool-background': "url('../public/subtle-prism.svg')",
      },
    },
  },
  plugins: [],
}
```

And then put a div around all of App.tsx

```
<div className="h-screen bg-cool-background">
    <div className="pt-2 pb-8 max-w-7xl mx-auto sm:px-6 lg:px-8">
....
</div>
```

There might be other ways to do it, but that seemed to be the most straightforward.

**Comment by muhelen** [comment]
Hi, thanks for the suggestion. Will try it out.
