### ISSUE TITLE
Add Description text on Settings

### ISSUE THREAD

**Issue by muhelen** [cwackerfuss/react-wordle#272]
<img width="526" alt="Screenshot 2022-02-25 at முற்பகல் 7 08 37" src="https://user-images.githubusercontent.com/5513469/155623056-8d68b4f6-893f-4565-8897-9e18413dfc5c.png">
Anyone knows how to add the description texts and styling same like the original version? It will look nicer with additional information on the button functions. Thanks.

**Comment by TheKnowles** [comment]
Good suggestion. Fixed in https://github.com/cwackerfuss/react-wordle/pull/274
