### ISSUE TITLE
Puzzle Number is zero based so the first puzzle is 0.

### ISSUE THREAD

**Issue by travisryan** [cwackerfuss/react-wordle#273]
**Describe the bug**
Most users won't want to think of puzzles as starting with 0. Most of the time that isn't an issue, but I just started mine and to be completely correct, I made a correction to add one to the Sharing clipboard copy text. (I just added one to solutionIndex).

In /src/lib/share.ts:
Old: navigator.clipboard.writeText(
    `${GAME_TITLE} ${solutionIndex} ${
      lost ? 'X' : guesses.length
    }/${MAX_CHALLENGES}${isHardMode ? '*' : ''}\n\n` +
      generateEmojiGrid(guesses, getEmojiTiles(isDarkMode, isHighContrastMode))
  )

New:  navigator.clipboard.writeText(
    `${GAME_TITLE} ${solutionIndex+1} ${
      lost ? 'X' : guesses.length
    }/${MAX_CHALLENGES}${isHardMode ? '*' : ''}\n\n` +
      generateEmojiGrid(guesses, getEmojiTiles(isDarkMode, isHighContrastMode))
  )

**Comment by igitur** [comment]
This was discussed and rejected in #89 .
