### ISSUE TITLE
Keyboard position on the bottom

### ISSUE THREAD

**Issue by muhelen** [cwackerfuss/react-wordle#278]
On the original version, the keyboard position on the bottom of the page looks great when viewing on desktops. It would be great if we could have similar to that look.

**Comment by cwackerfuss** [comment]
Thanks @muhelen - this should be done now, please confirm! Thanks

**Comment by muhelen** [comment]
Yes @cwackerfuss . Thanks. It's look great now 😊

**Comment by muhelen** [comment]
Hi, I've noticed on iOS the bottom address bar overlap the keyboard ![image](https://user-images.githubusercontent.com/5513469/155920420-fffaada8-bfb5-433f-89a8-2da49ecbffe4.png)
