### ISSUE TITLE
New layout changes cause unneeded horizontal scrolling and off-center layout

### ISSUE THREAD

**Issue by diondiondion** [cwackerfuss/react-wordle#284]
**Describe the bug**
See screenshot. (Firefox Mobile on Android)

**Screenshots**
![Screenshot_20220227-214231](https://user-images.githubusercontent.com/5636050/155899219-ba85dcef-df55-49fd-a780-70f607737586.png)

Most likely caused by #209

**Comment by cwackerfuss** [comment]
@diondiondion thanks for being so quick on mentioning this. This is breaking layout so I pushed a hotfix.. should look better now - can you take a look?

I also noticed the keyboard is a little below the bottom of the screen and you have to scroll to view it with the new flex grow behavior. I'll look into this and post a PR.

**Comment by diondiondion** [comment]
> can you take a look?

Thanks, that fixed it!
