### ISSUE TITLE
Use of 100vh causes keyboard to be covered up on iOS webkit browsers

### ISSUE THREAD

**Issue by vegeta897** [cwackerfuss/react-wordle#285]
**Overview**
The recently merged PR #209 added `h-screen` to the app container which uses `height: 100vh`. This technique for filling the screen is [known](https://stackoverflow.com/a/37113430/2612679) to cause the page to be "too tall" on iOS webkit browsers like Chrome and Safari. There are some hacky fixes out there but I don't know what approach would be best.

**To Reproduce**
1. Open reactle.vercel.app on a webkit browser (like Chrome or Safari) on iOS
2. Observe that the bottom part of the keyboard is hidden by browser UI, despite there being room above the keyboard

**Expected behavior**
The keyboard should be visible without scrolling down if there is room for it.

**Screenshots**
Chrome                                                                                                          |  Safari
:--------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------------------------------------------------:
![image](https://user-images.githubusercontent.com/1789096/155904447-89e12e79-319c-401e-a928-27e0abf7162b.png)  |  ![image](https://user-images.githubusercontent.com/1789096/155904451-3ac27a33-d168-4d9b-b9ec-69ae4d209811.png)

**Smartphone:**
 - Device: iPhone XS Max
 - OS: iOS15.3.1
 - Browser: Safari, Chrome

**Comment by diondiondion** [comment]
The simplest fix is probably just using % sizing instead of the vh unit. The downside is that `height: 100%` will have to be applied to every single ancestor of the element you want to fill the screen.

**Comment by oradwell** [comment]
I have a similar issue with Firefox mobile browser. the browser UI disappears if I scroll but still annoying

**Comment by TheKnowles** [comment]
@oradwell I'm collecting data points from https://github.com/cwackerfuss/react-wordle/pull/294

Could you please try this:

https://react-wordle-git-fork-theknowles-chrome-scro-8fcff7-cwackerfuss.vercel.app/

and let me know how that works.

**Comment by oradwell** [comment]
@TheKnowles lovely! it is not possible to scroll anymore but the game fits perfectly into the screen. happy with this

**Comment by igitur** [comment]
Fixed in #488 , #516
