### ISSUE TITLE
How do I create a custom, longer, success message?

### ISSUE THREAD

**Issue by ovisirb** [cwackerfuss/react-wordle#298]
How can I insert information in the "great job" or fail popup? i.e. if I have a cinema-related word, I want to also add a (HTML-compatible) description/definition of the word, regardless if the user guessed it or not. Where do I begin?

**Comment by TheKnowles** [comment]
String constants can be found here:

https://github.com/cwackerfuss/react-wordle/blob/main/src/constants/strings.ts

Specifically this line for the win messages:

https://github.com/cwackerfuss/react-wordle/blob/7d1a95b867d250bd060c4faa244b7eff9c929f10/src/constants/strings.ts#L3

**Comment by ovisirb** [comment]
Yes, I know about those, I was wondering if there's any chance of replacing the simple text popup with something that accepts html (i.e. to link certain definitions). As of now the HTML does not get parsed.

**Comment by igitur** [comment]
My opinion on this is it would be out of scope of this repo's goal of being a faithful Wordle clone and hence would be up the downstream repo to implement. I'm sure it's very possible, though.

**Comment by cwackerfuss** [comment]
@ovisirb what I'd do is allow [Alert.tsx](https://github.com/cwackerfuss/react-wordle/blob/main/src/components/alerts/Alert.tsx) to basically take the `message` prop as a `ReactNode` instead of a `string`. You will need to account for `message`'s value being `ReactNode` up the component tree in the `AlertContext` as well. Then you call it like so:
```
showSuccessAlert(<MyCustomAlertContent />)
```

**Comment by cwackerfuss** [comment]
Also note that if you do the above ^ the component you invoke will not respond to prop changes in a predictable way. If you depend on the `MyCustomAlertContent` component reacting to outside state changes, you need to use context or some other global state management.
