### ISSUE TITLE
Hamburger menu as original wordle

### ISSUE THREAD

**Issue by soumendrak** [cwackerfuss/react-wordle#301]
The [original wordle](https://www.nytimes.com/games/wordle/index.html) has a hamburger icon that opens a sidebar towards the left. Please implement.

![image](https://user-images.githubusercontent.com/10120538/156837318-2db82119-4cfe-436e-bf75-bca19c292016.png)

**Comment by abrarhayat** [comment]
Any idea what content we might want to show in the drawer? I am guessing, the only reason we don't have this is because we have no content to put in there. However, if there is some content we can show, I can add this hamburger icon with the drawer.

**Comment by gheja** [comment]
The hamburger menu is not part of the original Wordle, it was added when moved to the New York Times website, it contains the NYT specific stuffs.

I don't see any content that should be put in that.

What would be the use case?

**Comment by cwackerfuss** [comment]
Agreed with the above comments - if you look in the list these are NYT menu items - closing this :)
