### ISSUE TITLE
unit tests broken: ReferenceError: Cannot access 'mockSolutionGetter' before initialization

### ISSUE THREAD

**Issue by jleverenz** [cwackerfuss/react-wordle#302]
Two PRs went in recently that are not compatible.

* #252 introduced a module level dependency on `solution`
* #297 introduced new unit tests that attempt to mock `solution` out

From what I can tell tests on each PR passed, it's just once combined, the following error is generated:

```
FAIL src/lib/share.test.ts
  ● Test suite failed to run

    ReferenceError: Cannot access 'mockSolutionGetter' before initialization
```

Creating this issue to help track, I can propose a workaround soon.

**Comment by denik1981** [comment]
Can someone please review the PR(#330) I've submitted a few days ago? 
It should fix this testing issue.
