### ISSUE TITLE
Lint "Prettify code" workflow error

### ISSUE THREAD

**Issue by taximanli** [cwackerfuss/react-wordle#307]
**Describe the bug**
Lint "Prettify code" workflow error occurs when git push code changes to the forked github repository.

**To Reproduce**
1. git add .
2. git commit -m "Update description"
3. git push
4. See Prettify code error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11369846/157181273-a24760bb-da74-4a69-a915-648690d8e45e.png)

**Error Log**
Run creyD/prettier_action@v4.2
  with:
    prettier_options: --check src
    commit_message: Prettified Code!
    same_commit: false
    file_pattern: *
    dry: false
    prettier_version: false
    working_directory: false
    only_changed: false
    github_token: ***
Run PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh
  PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH /home/runner/work/_actions/creyD/prettier_action/v4.2/entrypoint.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    INPUT_COMMIT_MESSAGE: Prettified Code!
    INPUT_COMMIT_DESCRIPTION: 
    INPUT_SAME_COMMIT: false
    INPUT_COMMIT_OPTIONS: 
    INPUT_FILE_PATTERN: *
    INPUT_PRETTIER_OPTIONS: --check src
    INPUT_DRY: false
    INPUT_PRETTIER_VERSION: false
    INPUT_ONLY_CHANGED: false
    INPUT_PRETTIER_PLUGINS: 
    INPUT_WORKING_DIRECTORY: false
    INPUT_GITHUB_TOKEN: ***
Installing prettier...
Prettifying files...
Files:
Checking formatting...
[warn] src/components/alerts/Alert.tsx
[warn] src/components/grid/Cell.tsx
[warn] src/components/grid/Grid.tsx
[warn] src/components/keyboard/Bar.tsx
[warn] src/components/keyboard/Key.tsx
[warn] src/components/keyboard/Keyboard.tsx
[warn] src/components/modals/InfoModal.tsx
[warn] src/components/modals/SettingsModal.tsx
[warn] src/components/modals/SettingsToggle.tsx
[warn] src/components/modals/StatsModal.tsx
[warn] src/components/stats/Progress.tsx
[warn] src/components/stats/StatBar.tsx
[warn] src/constants/strings.ts
[warn] src/constants/validGuesses.ts
[warn] src/constants/wordlist.ts
[warn] src/lib/localStorage.ts
[warn] src/lib/share.ts
[warn] src/lib/statuses.ts
[warn] src/lib/words.ts
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
Problem running prettier with --check src
Error: Process completed with exit code 1.

**Comment by igitur** [comment]
Please post the direct link to this workflow execution.

**Comment by taximanli** [comment]
This is the direct link to the workflow execution. Thanks!
https://github.com/taximanli/kotobade-asobou/runs/5460712498?check_suite_focus=true

**Comment by igitur** [comment]
The linter is correct. Your code isn't formatted properly according to prettier's conventions. [Install prettier](https://prettier.io/docs/en/install.html) and format all your code files.

**Comment by gheja** [comment]
I'm not sure how you can check the changes before the linter does them but it won't stage automatically so you can fix and then check the differences.

To fix the formatting, simply run:
```bash
npm run fix
```

**Comment by igitur** [comment]
> ```shell
> npm run fix
> ```

On my Windows machine this changes the line endings from DOS style to Unix style, which is why I prefer running prettier explicitly using a VS Code plugin.
