### ISSUE TITLE
Infinitely many challenges

### ISSUE THREAD

**Issue by aghasemi** [cwackerfuss/react-wordle#313]
Hi,
Has anyone tried to (sort of) dynamically increase the maximum number of challenges after each guess, in order to create an "infinitely many challenges" effect?

**Comment by jaypatrick** [comment]
I'm working on this in my fork. I haven't finished it yet, but it'll be a service that fetches words from an upstream 3rd party API. It'll also allow for specifying the length of the word, as well as difficulty based on how common the word is (e.g. if you raise the "commonality", that lowers the difficulty, and vice-versa). It's still a work in progress, but I should have it done within a couple of weeks.
