### ISSUE TITLE
Viewport doesn’t fit on iOS browsers with url bar at bottom

### ISSUE THREAD

**Issue by jaypatrick** [cwackerfuss/react-wordle#314]
**Describe the bug**
On iOS, using Safari, and if the url bar is at the bottom, viewport is scrollable. All other iOS browsers I’ve tested with are fine, suspect it’s the bar being at the bottom that is throwing it off
**To Reproduce**
1. got to the test site for this git with Safari on iOS with url bar at bottom
2. Notice how viewport fit so it is scrollable. It shouldn’t be as all other browsers I’ve checked on iOS, viewport is a perfect fit

**Expected behavior**
Viewport should not scroll on any browser

**Screenshots**
see attached video

**Additional context**
I am a downstream fork. I have some interesting stuff I’m working on for dynamic dictionary lookup instead of hard coded ( or alongside). Awesome work, I’m learning a lot about react, Cindy, after tech years as a backend dude. This is a great project to learn in!

**Comment by jaypatrick** [comment]
W00t

**Comment by igitur** [comment]
Fixed in #488 , #516
