### ISSUE TITLE
Centre placement of grid

### ISSUE THREAD

**Issue by rachaera** [cwackerfuss/react-wordle#316]
After deploying a version of wordle, i noticed via developer tools that the grid isnt place in the centre ; making the space between the grid and keyboard huge. anyway to get around this?
![Screenshot 2022-03-11 at 11 49 19 PM](https://user-images.githubusercontent.com/100667491/157927042-8cf97db0-6ad0-426b-9f18-0f0983e8e792.png)

**Comment by jleverenz** [comment]
You should be able to adjust css for a different layout. For center-aligning the grid, try:

```
diff --git a/src/App.tsx b/src/App.tsx
index 928d7e3..d269711 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -248,7 +248,7 @@ function App() {
         setIsSettingsModalOpen={setIsSettingsModalOpen}
       />
       <div className="pt-2 px-1 pb-8 md:max-w-7xl w-full mx-auto sm:px-6 lg:px-8 flex flex-col grow">
-        <div className="pb-6 grow">
+        <div className="pb-6 grow flex flex-col justify-center">
           <Grid
             guesses={guesses}
             currentGuess={currentGuess}
```

<img width="220" alt="Screen Shot 2022-03-12 at 9 36 48 AM" src="https://user-images.githubusercontent.com/11267/158024560-ccf76f66-78ff-425b-810b-29399bc4aed7.png">


Here's another variant, aligning to the bottom:

```
diff --git a/src/App.tsx b/src/App.tsx
index 928d7e3..5126149 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -247,8 +247,8 @@ function App() {
         setIsStatsModalOpen={setIsStatsModalOpen}
         setIsSettingsModalOpen={setIsSettingsModalOpen}
       />
-      <div className="pt-2 px-1 pb-8 md:max-w-7xl w-full mx-auto sm:px-6 lg:px-8 flex flex-col grow">
-        <div className="pb-6 grow">
+      <div className="pt-2 px-1 pb-8 md:max-w-7xl w-full mx-auto sm:px-6 lg:px-8 flex flex-col grow justify-end">
+        <div className="pb-6">
           <Grid
             guesses={guesses}
             currentGuess={currentGuess}
```
<img width="217" alt="Screen Shot 2022-03-12 at 9 36 07 AM" src="https://user-images.githubusercontent.com/11267/158024533-6946089e-6c7d-4520-b72a-645d472a7310.png">

**Comment by rachaera** [comment]
@jleverenz it worked perfectly ; thank you so much !!! hope you're having/had a lovely day ~
