### ISSUE TITLE
Daylight Savings Time shifted next word start by an hour

### ISSUE THREAD

**Issue by TrevorSayre** [cwackerfuss/react-wordle#321]
**Describe the bug**
We just had Daylight Savings Time in the US, and the next puzzle is off by an hour (1am instead of 12am).

**To Reproduce**
This one may be a bit tricky to reproduce... you'll have to mock the time during a daylight savings time shift...

**Expected behavior**
The next word should be available at midnight. Instead it's available at 1am after the "spring forward" daylight savings time shift.

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1 
 - Browser: Chrome
 - Version: 99.0.4844.51

**Comment by igitur** [comment]
The real fix is to petition your local government representative to abolish daylight savings time.

**Comment by igitur** [comment]
Only a slight tongue in cheek comment 🤪

**Comment by praneeth-m** [comment]
I'm sure there's a better way to fix it but here's what I did to apply a quick fix.
Inside /src/lib/words.ts, add the following code:

`declare global {
  interface Date {
    stdTimezoneOffset(): any
    isDstObserved(): any
  }
}
// eslint-disable-next-line no-extend-native
Date.prototype.stdTimezoneOffset = function () {
  var jan = new Date(this.getFullYear(), 0, 1)
  var jul = new Date(this.getFullYear(), 6, 1)
  return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset())
}
// eslint-disable-next-line no-extend-native
Date.prototype.isDstObserved = function () {
  return this.getTimezoneOffset() < this.stdTimezoneOffset()
}

// right after we define epochMs, add this code below:
var today = new Date()
  if (today.isDstObserved()) {
    epochMs = epochMs - 3600000 // adjust for DST and remove an hour (3600000 ms)
  }`

That should do it.

**Comment by praneeth-m** [comment]
I'm sure there's a better way to fix it but here's what I did to apply a quick fix.
Inside /src/lib/words.ts, add the following code:

```
declare global {
  interface Date {
    stdTimezoneOffset(): any
    isDstObserved(): any
  }
}
// eslint-disable-next-line no-extend-native
Date.prototype.stdTimezoneOffset = function () {
  var jan = new Date(this.getFullYear(), 0, 1)
  var jul = new Date(this.getFullYear(), 6, 1)
  return Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset())
}
// eslint-disable-next-line no-extend-native
Date.prototype.isDstObserved = function () {
  return this.getTimezoneOffset() < this.stdTimezoneOffset()
}

// right after we define epochMs, add this code below:
var today = new Date()
if (today.isDstObserved()) {
  epochMs = epochMs - 3600000 // adjust for DST and remove an hour (3600000 ms)
}
```

That should do it.

**Comment by vegeta897** [comment]
There's a much better/cleaner way of doing it, I just implemented it in my own project. I'll make a PR.
