### ISSUE TITLE
Found invalid word

### ISSUE THREAD

**Issue by bellalalavv** [cwackerfuss/react-wordle#323]
![Screenshot_20220314-195912](https://user-images.githubusercontent.com/83415053/158168104-d10235b4-f2bb-43d3-bb39-18908d6800e1.png)
The word "spoil" is not found in the dictionary

**Comment by jleverenz** [comment]
I was not able to reproduce this on current `main` @ `a43feab6a859083dddb3aa3577b2ac4ad909bdf1`. SPOIL passed as a valid guess, and I also confirmed it's in the list: https://github.com/cwackerfuss/react-wordle/blob/main/src/constants/validGuesses.ts#L10598

**Comment by gheja** [comment]
I believe this issue is for a fork.

I checked the URL seen on the screenshot, the About modal says:

> This is a game of word guessing with BTS related words, created by [hannahcode](https://github.com/hannahcode/GAME) and modified by [BTSCHARTDATA](https://twitter.com/btschartdata).
