### ISSUE TITLE
Not accepting the answer

### ISSUE THREAD

**Issue by pizzalover1323** [cwackerfuss/react-wordle#329]
The word for today (March 17th) is "slays", because it has to be. I entered it twice and it's not accepting it. Tried all 25 other letters at the end there just to be safe, but since that last "s" isn't even yellow I'm pretty sure it's just a bug. No idea how one would fix this, haha, I'm just reporting. 

![Screenshot 2022-03-17 1 22 17 AM](https://user-images.githubusercontent.com/101788845/158749564-66cc3649-e3d7-4fcd-80f0-a03d4cf7fb39.png)

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/158771082-1c773fb1-265e-4002-bd34-f338454ef4cf.png)

Works fine in latest `main`. Please rebase your repo on `main`.
