### ISSUE TITLE
Share button does not seem to work as intended

### ISSUE THREAD

**Issue by modem7** [cwackerfuss/react-wordle#331]
**Describe the bug**
Share button does not seem to work as intended.

When clicked, it does not do anything.

**To Reproduce**
Steps to reproduce the behaviour:
```bash
git clone https://github.com/cwackerfuss/react-wordle.git &&
cd react-wordle/ &&
docker build --no-cache --target=prod -t wordle:test -f docker/Dockerfile . &&
docker run -d -p 80:8080 --name reactle-prod wordle:test &&
cd ../ && rm -rf ./react-wordle
```
Enter words, click share. 

**Expected behaviour**
For share to copy to clipboard. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4349962/159040115-48287e01-25d4-4206-882b-ae6636a2ee30.png)

**Additional context**
Tested on Vivaldi and Edge

**Comment by igitur** [comment]
What device are you using exactly?

**Comment by modem7** [comment]
> What device are you using exactly?

Bog standard Windows 10 PC. 

I've also tested it on Android (Oneplus 9) with the same results.

**Comment by Marantle** [comment]
I had this same problem but realized it wont work without being secure, are you running the app in secure context, https, when you are testing this?
as per https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
_Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers._

**Comment by modem7** [comment]
> I had this same problem but realized it wont work without being secure, are you running the app in secure context, https, when you are testing this? as per https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share _Secure context: This feature is available only in secure contexts (HTTPS), in some or all supporting browsers._

Great catch, thank you! 

Can confirm that hosting it via https instead of local works with this functionality. 

Cheers again!
