### ISSUE TITLE
Is it currently possible to have words of different lengths?

### ISSUE THREAD

**Issue by eltaylor1104** [cwackerfuss/react-wordle#346]
Hi there,

Is it currently possible to fill the wordlist with words of different lengths and have the game display the proper number of squares for the amount of letters in todays word? (so that people could have words of different lengths in their wordlist?)

**Comment by jleverenz** [comment]
This should be possible. Check out #252 and a related (unmerged) refactor in #310.

**Comment by cwackerfuss** [comment]
This is now merged @jleverenz and @eltaylor1104
