### ISSUE TITLE
Including words of different length

### ISSUE THREAD

**Issue by kstewordle** [cwackerfuss/react-wordle#353]
Does anyone know how to change the code so that I include words of different lengths? I am trying to create a wordle clone that has people guess words between 4-6 letters once a day. Thanks so much!

**Comment by igitur** [comment]
There is an attempt to address this at #310.

**Comment by Objectivitix** [comment]
The word length is dynamic - by updating `validGuesses.ts` and `wordlist.ts`, you should be able to change the length without further code modifications. In your case, this means adding the 4- and 6-letter words in both lists.

**Comment by cwackerfuss** [comment]
#310 is now merged.
