### ISSUE TITLE
Add CVErdle to README

### ISSUE THREAD

**Issue by benzies** [cwackerfuss/react-wordle#362]
Just promoting your code by utilising another puzzle game. Got features to add, but I think it's off to a good start. Aim is to help teach more Cybersecurity to the world. https://www.cverdle.io/

It'll fall nicely under the title 'Math, Acronyms, Science, Tech, and more'

Thanks

**Comment by igitur** [comment]
Please submit a PR for this. You can do this on your local machine or edit the README.md directly on Github.
