### ISSUE TITLE
How to add HTTPS/SSL to the project?

### ISSUE THREAD

**Issue by xjcl** [cwackerfuss/react-wordle#369]
I'm trying to deploy the project with HTTPS as the share button isn't working over HTTP.

I'm confused exactly about how to go about this, here are 2 approaches I thought about:
- Bake an SSL certificate and a different `nginx` configuration into the Docker image. I suspect this won't work because SSL certificates are bound to a certain domain/URL and the Docker container can't possibly know the domain it is running on right?
- Additionally install `nginx` on the host system and "forward" the HTTPS traffic on port 443 some other port that the docker container listens on (say 80), instead of exposing the Docker port to the outside world directly. This seems very complicated. When forwarding the traffic, is it decrypted, so the `nginx` inside the Docker container can use it?

Which approach would work?

(Both approaches seem to have the downside of being HTTPS-only rather than allowing both HTTP and HTTPS.)

I was looking at this guide, is this somewhat close to what you need to do? https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-18-04

**Comment by modem7** [comment]
Look at NPM - Nginx Proxy Manager. 

It's the recommended way of doing things via Docker. 

Sharing via HTTP won't work as per https://github.com/modem7/react-wordle/issues/14#issuecomment-1073261043, unfortunately.
