### ISSUE TITLE
Add hard mode

### ISSUE THREAD

**Issue by diondiondion** [cwackerfuss/react-wordle#37]
Like in the original Wordle, it'd be useful to add a mode where previous hints must be taken into account on subsequent tries, to help users choose the words with the best "new character" yield.

**Comment by TheKnowles** [comment]
https://github.com/cwackerfuss/react-wordle/pull/138

**Comment by diondiondion** [comment]
> #138

Thanks for implementing this @TheKnowles!

I would argue that the icons used for indicating the mode (which are very well chosen, btw! 😅) are being displayed the wrong way around, i.e. unlike the dark mode toggle they don't show the target mode that will be active after a click, but the mode you're currently in.

**Comment by TheKnowles** [comment]
It is unclear. I've created a settings modal and moved hard mode toggle there.

https://github.com/cwackerfuss/react-wordle/pull/146

**Comment by diondiondion** [comment]
Closing this as the basic functionality was implemented. Thanks again @TheKnowles
