### ISSUE TITLE
Add a notification about failing to properly execute Share

### ISSUE THREAD

**Issue by gheja** [cwackerfuss/react-wordle#371]
The Share feature only works when the page is loaded over HTTPS.

See these issues:
https://github.com/cwackerfuss/react-wordle/issues/331
https://github.com/cwackerfuss/react-wordle/issues/367

The Share button now silently ignores the failure of copying to clipboard.

It might fail silently under other conditions as well.

I believe it would be the best to give a notification to the player about this failure. (This would be more robust than trying to detect if the requirements are met before pressing the Share button, IMHO.)

**Comment by igitur** [comment]
I'll take this. Ironically, it's difficult to replicate on localhost, because localhost is actually a trusted domain.

**Comment by igitur** [comment]
What should the exact notification be?

`Unable to share the results. This feature is available only in secure contexts (HTTPS), in some or all supporting browsers.` 

?

**Comment by igitur** [comment]
![image](https://user-images.githubusercontent.com/145854/161931289-846e3ece-439c-4152-a1a8-be4d59204b53.png)

**Comment by igitur** [comment]
As a fallback, we could show a new modal dialog with a textbox with the share content, so that the user can manually copy and paste the results?

**Comment by gheja** [comment]
Oh, that would be handy!

Also, then we could display the full text like above, we would not have to worry about the timeout of the message.

I might be wrong but maybe there was a similar modal before? Or was/is it Wordle?

**Comment by igitur** [comment]
> I might be wrong but maybe there was a similar modal before? Or was/is it Wordle?
I've never seen that, so I don't know.

Ok, I've got a fix for this ready. But it seems a more robust fix is to implement the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions). I can't recall that I ever had to grant permission for Wordle or Reactle, but it seems like clipboard write permissions are usually enabled by default, but clipboard read permissions (not relevant to us) need explicit permission. Example: https://async-clipboard-api.glitch.me/
