### ISSUE TITLE
Fix Reactle to shrink word grid to be smaller on smaller displays

### ISSUE THREAD

**Issue by Zfauser** [cwackerfuss/react-wordle#375]
**Is your feature request related to a problem? Please describe.**
On small screens you must scroll up and down and up and down to type on the keyboard then view your results

**Describe the solution you'd like**
Shrink the word grid like in the official wordle

**Describe alternatives you've considered**
Maybe shrinking the keyboard could also work

**Additional context**
https://user-images.githubusercontent.com/19974370/162636770-cc2e0e46-d137-474d-be21-9c6797683924.mp4
https://user-images.githubusercontent.com/19974370/162636774-e383577f-d607-4a94-a446-ad245901024c.png

**Comment by modem7** [comment]
Might be related to https://github.com/cwackerfuss/react-wordle/issues/314

**Comment by Zfauser** [comment]
> Might be related to/resolved by #285 and #314
Maybe, but the fixes in pr #294 still don't make the game playable without scrolling up and down on smaller devices
![Screen Shot 2022-04-22 at 9 06 41 PM](https://user-images.githubusercontent.com/19974370/164845182-e6ce9a9e-500e-4932-a74a-242069a0b92b.png)

**Comment by wesgurn** [comment]
Still seeing this issue.  Any updates on this?

**Comment by igitur** [comment]
Fixed in #488 , #516
