### ISSUE TITLE
How can one remove the timer for an endless wordle?

### ISSUE THREAD

**Issue by Coolbeans007** [cwackerfuss/react-wordle#394]
Im trying to remove the daily timer to make the app get a new word everytime the user refreshes the page.
Or better yet make it just one min becasue 24 hours is too long.

**Comment by btahir** [comment]
Having this issue as well. It seems the code has been refactored so previous suggestions about updating msInDay are not working anymore. It seems the date logic is now using a lot of day specific logic from 'date-fns' so would appreciate any pointers on how to make this update more frequently.
