### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Cohejh** [cwackerfuss/react-wordle#406]
I do not know how to put the file on my website.

**Comment by Cohejh** [comment]
(Am new to JS)

**Comment by igitur** [comment]
Maybe I'm the bad cop here, but I think general coding questions should be referred to StackOverflow.

@cwackerfuss Agree?

**Comment by Cohejh** [comment]
OK, what is stackoverflow?

**Comment by Cohejh** [comment]
Oh wait, sorry i found it.
