### ISSUE TITLE
[Feature Request] Multi-user

### ISSUE THREAD

**Issue by lonix1** [cwackerfuss/react-wordle#432]
It would be nice to have a multi-user feature:
- there is a new word every day
- you can login with your username/password
- you and your coworkers can play the game once each day
- you can view the scores/rankings every day

I think one word per day is enough, else the boss would get angry for time wasting.

It would be a nice little diversion and exercise in daily camaraderie.

I don't know react and so cannot help unfortunately. If out of scope, please feel free to close this issue.

**Comment by igitur** [comment]
I think this is out of scope for this project, which aims to be a fairly faithful Wordle clone. Besides that, your requests imply setting up a database and server-side functionality, which is not supported by this project at all. This is a pure client-side solution.

**Comment by lonix1** [comment]
I don't know what is Wordle, I just arrived here and enjoyed the demo game. If there is no backend though, then I suppose there's nothing to be done. Thanks for your explanation.

**Comment by igitur** [comment]
> I don't know what is Wordle

Wordle is the original game. This is a clone of it. The original Wordle is played at https://www.nytimes.com/games/wordle/index.html
