### ISSUE TITLE
Old Word Archive

### ISSUE THREAD

**Issue by muhelen** [cwackerfuss/react-wordle#500]
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to go back in time to do words of past days. An Archive modal would be a great idea.

**Comment by igitur** [comment]
On my downstream implementation, https://worteltjie.wrintiewaar.co.za I have built in an archive function. I might submit it as a PR to this repo later. Let me know how you find the way it works.

**Comment by igitur** [comment]
On my downstream implementation, https://wortel.wrintiewaar.co.za I have built in an archive function. I might submit it as a PR to this repo later. Let me know how you find the way it works.

**Comment by muhelen** [comment]
> On my downstream implementation, https://wortel.wrintiewaar.co.za I have built in an archive function. I might submit it as a PR to this repo later. Let me know how you find the way it works. 

Yes this looks great. Waiting for your PR. Thanks.
