### ISSUE TITLE
Croatian Wordle: Using incorrect and curse words

### ISSUE THREAD

**Issue by DrWords** [cwackerfuss/react-wordle#580]
Another day, another problem!
Not only is today's word a conjugated one, but now you are also offering expletives!
"SEREŠ" = You sh*t. 

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by igitur** [comment]
Wrong repo, again.
