### ISSUE TITLE
Would like to add a feature, when game is solved for the day

### ISSUE THREAD

**Issue by kiyanpourmaleki** [cwackerfuss/react-wordle#638]
Would like to keep a message up after site is loaded and game is won for the day. After the popup for stats comes up, the win message goes away. I would like to add a message that remains up saying something along the lines of "thanks for playing todays reaclte, next game in HH:MM:SS.

Thoughts?

**Comment by cozmo14047** [comment]
i would love to do this too i did try but keept getting big messages with error

**Comment by igitur** [comment]
This is possible, but outside the scope of this project. You'll have to code it yourself in your derivative work.
