### ISSUE TITLE
Carnt find the file for how to play popup

### ISSUE THREAD

**Issue by cozmo14047** [cwackerfuss/react-wordle#664]
Ive looked every where and i just carnt find the how to play pop up code could someone please give me the directory

**Comment by igitur** [comment]
https://github.com/cwackerfuss/react-wordle/tree/main/src/components/modals

**Comment by igitur** [comment]
https://github.com/cwackerfuss/react-wordle/blob/main/src/components/modals/InfoModal.tsx

**Comment by cozmo14047** [comment]
Thank you
