### ISSUE TITLE
Is lint-stage missing a ** for recursive checking?

### ISSUE THREAD

**Issue by nate-h** [cwackerfuss/react-wordle#667]
**Describe the bug**
I think this:
```json
"lint-staged": {
    "src/*.{ts,tsx,js,jsx,css,md}": "prettier --write"
  },
```
should be this:
```json
"lint-staged": {
    "src/**/*.{ts,tsx,js,jsx,css,md}": "prettier --write"
  },
```

I'm not sure you guys are intentionally not running this to keep things a little less aggressive.

**To Reproduce**
try modifying a nested file and see if husky actually runs

**Expected behavior**
I'm only reading the source and noticing this might be missing

**Comment by igitur** [comment]
Will check it out, thanks.

**Comment by igitur** [comment]
Thanks for highlighting this. Now fixed.
