### ISSUE TITLE
Nice implementation - I did something analogous, might be interesting

### ISSUE THREAD

**Issue by lubianat** [cwackerfuss/react-wordle#705]
Hey, I just found out your code! 

I've done a very similar thing back then: https://github.com/lubianat/gene-wordle 

Idk, maybe the implementation diffs can bring some ideas,
cheers

**Comment by igitur** [comment]
I don't understand. https://github.com/lubianat/gene-wordle is a fork of this repo, with some additional commits. How did you just find the code right now?

**Comment by lubianat** [comment]
Oh damn, it is the link on https://andrewholding.github.io/gene-wordle/

It was a link to the original, not to the fork, oops
