### ISSUE TITLE
Adding Wordle Català

### ISSUE THREAD

**Issue by soyTorch** [cwackerfuss/react-wordle#717]
Problem:
I would like to add "Wordle Català (Wordle Cat)" (http://wordle-catala.cat/) to the list of all Wordle games in the readme.md file.

Solution:
I suggest adding a new entry for "Wordle Català (Wordle Cat)" to the list of Wordle games in the readme.md file.

Alternatives Considered:
I haven't considered any alternative solutions as this is a straightforward addition to the readme.md file.

Additional Context:
Please include the link to "Wordle Català (Wordle Cat)" (http://wordle-catala.cat/) in the list of Wordle games for reference.

Thanks in advance

**Comment by igitur** [comment]
Please submit a pull request to add it to the README.
