### ISSUE TITLE
Unfamiliar and unexpected behavior allowing the plural form with S at the end of words.

### ISSUE THREAD

**Issue by rlguibord** [cwackerfuss/react-wordle#730]
It seems there is a desire to preserve the behavior of the original game. One thing different here that I find disconcerting is that the use of S is allowed to indicate a plural form of the word. My understanding is that this is not in line with the behavior of the original. Can this be changed, or made an option?

**Comment by igitur** [comment]
This repo was a pet project by the original author and is now meant as base for others to implement their own derivative versions.

You're free to changed the list of allowed words in your own version as you see fit.
