### ISSUE TITLE
Feature idea: Gameshow mode

### ISSUE THREAD

**Issue by StevenH237** [cwackerfuss/react-wordle#93]
A certain game show that this is similar to has a couple rules that would provide an intriguing change to gameplay:

* You only get five guesses, not six.
* The first letter of the word is revealed at the start. All guesses must start with this letter, even though not using other hints is allowed.

**Comment by cwackerfuss** [comment]
@StevenH237 closing this to clean up the board since it's a fork idea. If you end up building this feel free to let us know!
